hubzero/hubzero-cms

- core/components/com_update/admin/language/en-GB/en-GB.com_update.ini
- core/components/com_update/api/controllers/updatev1_0.php
- core/components/com_update/api/router.php
- core/components/com_update/config/config.xml
This is a mechanism meant for QA machines that allow webhooks to initiate a git update.
> Gitupdater

- core/migrations/Migration20170124151456ComSupport.php
> Ticket migration to add mp4 to support file types.

- core/components/com_wishlist/models/plan.php
- core/components/com_wishlist/tables/wish/plan.php
Proposed resolution for Nanohub ticket #320801.
> Nano 320801

- core/components/com_answers/site/views/questions/tmpl/search.php
- core/plugins/resources/questions/views/browse/tmpl/default.php
Proposed resolution for Nanohub ticket #320771.
> Nano 320771

- core/components/com_projects/site/controllers/media.php
- core/components/com_projects/site/views/projects/tmpl/_image.php
Proposed resolution for HUBzero ticket #10635.
> Zero 10635

- core/components/com_feedback/site/controllers/feedback.php
Allows for newlines to be included and rendered in success stories
> [HUBZERO][#10604][COM_FEEDBACK] Update Feedback#sendstoryTask

- core/components/com_kb/site/controllers/articles.php
- core/components/com_kb/site/router.php
Update variable semantics
To prevent ambiguous lookup, Articles are now retrieved by their alias
and category ID
> [HUBZERO][#10639][COM_KB] Update Article lookup code

- core/plugins/groups/announcements/views/email/tmpl/announcement_html.php
Improves readability by relocating group announcement page link
> [NCIP][#1384][PLG_GROUPS] Update group announcements template

- core/components/com_dataviewer/site/controller.php
- core/components/com_dataviewer/site/filter/json.php
- core/components/com_dataviewer/site/view/gallery.php
> [COM_DATAVIEWER] Fixed the gallery view

- core/components/com_dataviewer/site/filter/json.php
Removed #dv_top suffix from filtering urls
> [COM_DATAVIEWER] Removed #dv_top suffix from filtering urls

- core/components/com_projects/models/adapters/nogit.php
> [PURR][#1492][COM_PROJECTS] Update nogit adapter

- core/components/com_members/models/incremental/groups.php
- core/modules/mod_incremental_registration/helper.php
Fixes flag to not show on error pages, limits questions per interaction to reduce annoyance potential.
> [MOD_INCREMENTAL_REGISTRATION][nanoHUB #319790]

- core/components/com_members/site/assets/js/orcid.js
- core/components/com_members/site/language/en-GB/en-GB.com_members.ini
- core/components/com_members/site/views/orcid/tmpl/display.php
ORCID fetchTask is executed twice after clicking on the "Search ORCID" button.
Operation procedure: Login on PURR -> Go to Profile -> ORCID -> Click on "Find your ID" -> Click on "Search ORCID". 
The reason is that there are two click event handlers are attached to the "Search ORCID" button, one is in the onClick property of the button itself and another is the registered via the HUB.Orcid.fetchOrcid method.  The latter is removed from the code to fix the issue.
>  [PURR][#1537]Fix the issue that ORCID fetch task is executed twice

- core/components/com_projects/helpers/layoutHelper.php
- core/components/com_projects/site/controllers/projects.php
- core/plugins/projects/files/files.php
[MYGEOHUB][#1191][COM_PROJECTS][PLG_PROJECTS_FILES]
https://mygeohub.org/support/ticket/1191
> Allow non-member access to public project files

- core/components/com_members/site/controllers/orcid.php
Fix the issue that names are missing for partial of the ORCID searching results.
Login -> Profile -> Search by any last name and the results shows that names are missing for some ORCID records in the searching result.
> [PURR][#1539]Fix the name missing issue in ORCID searching result

- core/components/com_members/site/assets/js/orcid.js
- core/components/com_members/site/controllers/orcid.php
- core/components/com_members/site/language/en-GB/en-GB.com_members.ini
- core/components/com_members/site/views/orcid/tmpl/display.php
Need merge the fix in core/components/com_members/site/controllers/orcid.php to production PURR.
> [PURR][#1556]Fix the name missing issue in ORCID searching result

- core/components/com_projects/site/controllers/projects.php
Add additional check to conditional that throws 403 for private project
> Update com_projects projects controller

- core/migrations/Migration20171115112800ComSupportCriteria.php
- core/migrations/Migration20171215082900ComSupportCriteriaQueryText.php
Changes jos_support_criteria#query from varchar(255) to text
> Implement migration to udpate jos_support_criteria

- core/plugins/user/xusers/xusers.php
Fix query referencing undefined table alias
> [PLG_XUSERS_XUSERS] Fixes query string.

- core/migrations/Migration20130924000002Core.php
- core/migrations/Migration20130924000005Core.php
- core/migrations/Migration20130924000009ComMenus.php
- core/migrations/Migration20140528145010ComRegister.php
- core/migrations/Migration20141202211549PlgMembersDashboard.php
- core/migrations/Migration20150626201931Core.php
- core/migrations/Migration20151030000001ComCart.php
- core/migrations/Migration2016090510300000Core.php
- core/migrations/Migration2016090511300000Core.php
- core/migrations/Migration2016090610030000ComTools.php
- core/migrations/Migration2016090610110000Core.php
- core/migrations/Migration2016090710240000ComCourses.php
- core/migrations/Migration2016090710280000ComCategories.php
- core/migrations/Migration2016090710350000ComBillboards.php
- core/migrations/Migration2016090710430000ComCart.php
- core/migrations/Migration2016090710490000ComCore.php
- core/migrations/Migration2016090710490000Core.php
- core/migrations/Migration2016090710530000ComUsers.php
- core/migrations/Migration2016090710560000ComSupport.php
- core/migrations/Migration2016090711260000Core.php
- core/migrations/Migration20161017133711ComMembers.php
- core/migrations/Migration20161018093917Core.php
- core/migrations/Migration20161021135212ComUsers.php
- core/migrations/Migration20170322093811ComResources.php
Migration fixes from 2.1 branch used when upgrading very old hubs.
> Old migrations

- core/components/com_members/models/fields/orcid.php
It is suggested that user can directly connect to the ORCID directly instead of searching the ORCID by name and choose one from the result list. The changes reflects the requirement.
> [PURR][#1575]Launch the ORCID create-or-connect directly

- core/components/com_members/site/controllers/register.php
- core/components/com_members/site/views/emails/tmpl/confirm.php
- core/components/com_members/site/views/emails/tmpl/confirm_html.php
- core/components/com_members/site/views/emails/tmpl/create.php
- core/components/com_members/site/views/emails/tmpl/create_html.php
- core/components/com_members/site/views/emails/tmpl/update.php
- core/components/com_members/site/views/emails/tmpl/updateproxy.php
- core/components/com_members/site/views/register/tmpl/default.php
- core/components/com_users/site/controllers/user.php
- core/plugins/authentication/emailtoken/emailtoken.php
- core/plugins/authentication/emailtoken/emailtoken.xml
- core/plugins/authentication/emailtoken/language/en-GB/en-GB.plg_authentication_emailtoken.ini
- core/plugins/authentication/emailtoken/language/en-GB/en-GB.plg_authentication_emailtoken.sys.ini
- core/plugins/authentication/emailtoken/migrations/Migration20180201000000PlgAuthenticationEmailtoken.php
Added a plugin to support this feature along with having the confirmation email pass along another parameter.
> Changes to support automatic login when confirming email address

- core/components/com_projects/helpers/accessHelper.php
- core/components/com_projects/site/controllers/projects.php
- core/plugins/projects/files/files.php
com_projects
plugins/projects/files
Authenticated users can now access the interface for a project's files
located in the top-level public directory
Refs: https://mygeohub.org/support/ticket/1191
> [feat] Allow authenticated users to access /public

- core/plugins/projects/files/assets/js/fileupload.jquery.js
fixes: https://purr.purdue.edu/support/ticket/1641
> [fix] Update projects files upload alert

- core/plugins/projects/files/assets/js/fileupload.jquery.js
- core/plugins/projects/files/views/upload/tmpl/default.php
Added a list to allow file types that the upload library does not
recognize
fixes: https://purr.purdue.edu/support/ticket/1682
> [fix] Update projects files upload notification

- core/plugins/projects/files/assets/js/fileupload.jquery.js
Account for possible file extension capitalization
Remove alert message from version control
Fixes: https://purr.purdue.edu/support/ticket/1682
> Update projects file upload format checking

- core/plugins/projects/files/views/connected/tmpl/_item.php
- core/plugins/projects/files/views/connected/tmpl/_item_link.php
- core/plugins/projects/files/views/connected/tmpl/_item_link_directory.php
- core/plugins/projects/files/views/connected/tmpl/_item_link_file.php
- core/plugins/projects/files/views/connected/tmpl/_items.php
Ideally this should be merged after https://github.com/hubzero/hubzero-cms/pull/242
> Ncip 1453 master

- core/components/com_developer/site/controllers/callback.php
- core/composer.json
- core/composer.lock
- core/plugins/filesystem/dropbox/dropbox.php
- core/plugins/filesystem/dropbox/helpers/dropboxOauthClient.php
- core/plugins/projects/files/views/connected/tmpl/_item.php
- core/plugins/projects/files/views/connected/tmpl/_item_link_file.php
- core/plugins/projects/publications/publications.php
Replaced league/flysystem-dropbox with srmklive/flysystem-dropbox-v2
Implemented DropboxOauthClient wrapper for stevenmaguire/oauth2-dropbox
Refactored com_developer/site/controllers/callback.php Dropbox code
Removed MIME type check from plugins/projects/files/connected items view
fixes: https://nciphub.org/support/ticket/1454
> [fix] Update projects files Dropbox connector

- core/plugins/authentication/shibboleth/fields/get-rs-entities.php
Trying this again, hopefully having reset my fork properly
> change InCommon metadata URL to reflect upstream change

- core/components/com_resources/models/entry.php
Fixes: https://qubeshub.org/support/ticket/1136
> [fix] Fixing incorrectly named property

- core/components/com_members/helpers/utility.php
>  fix validemail registration check to allow longer label parts

- core/plugins/projects/files/views/connected/tmpl/_item_link_file.php
Refs: https://developers.google.com/drive/api/v3/mime-types
Fixes: https://qubeshub.org/support/ticket/1202
> [fix] Handle some lesser known Google mime types

- core/components/com_projects/admin/controllers/projects.php
- core/components/com_projects/admin/language/en-GB/en-GB.com_projects.ini
- core/components/com_projects/admin/views/projects/tmpl/display.php
- core/components/com_projects/migrations/Migration20180701000000ComProjects.php
This allows for marking a project as being 'featured' or not. This will
be used in front-end browsing/filtering and possibly modules.
> [feat] Adding a 'featured' column to projects

- core/components/com_cart/admin/controllers/downloads.php
- core/components/com_cart/helpers/Download.php
Change how metadata is retrieved and stream it to the client without buffering
> (2.2) [fix] Enable large downloads for com_cart downloads 

- core/components/com_cart/admin/controllers/downloads.php
- core/components/com_cart/helpers/Download.php
Change how metadata is retrieved and stream it to the client without heavy buffering
> [fix] Enable large downloads for com_cart downloads

- core/components/com_projects/site/controllers/setup.php
- core/components/com_projects/tables/owner.php
- core/plugins/projects/team/assets/css/selector.css
- core/plugins/projects/team/assets/js/team.js
- core/plugins/projects/team/language/en-GB/en-GB.plg_projects_team.ini
- core/plugins/projects/team/views/edit/tmpl/default.php
[refs] https://nciphub.org/support/ticket/1476
> [feat] Implement selective group project role sync

- core/plugins/groups/calendar/calendar.php
Fixes: https://help.hubzero.org/support/ticket/11472
> [fix] Input casting and better validation

- core/components/com_members/admin/controllers/members.php
Refs: https://help.hubzero.org/support/ticket/11418
> [fix] Clear out login failures after password resets

- core/components/com_storefront/admin/controllers/collections.php
- core/components/com_storefront/admin/controllers/images.php
- core/components/com_storefront/admin/controllers/meta.php
- core/components/com_storefront/admin/controllers/optiongroups.php
- core/components/com_storefront/admin/controllers/options.php
- core/components/com_storefront/admin/controllers/products.php
- core/components/com_storefront/admin/controllers/restrictions.php
- core/components/com_storefront/admin/controllers/serials.php
- core/components/com_storefront/admin/controllers/skus.php
- core/components/com_storefront/admin/controllers/whitelist.php
- core/components/com_storefront/admin/views/restrictions/tmpl/new.php
- core/components/com_storefront/admin/views/restrictions/tmpl/upload.php
- core/components/com_storefront/admin/views/restrictions/tmpl/uploadcsv.php
- core/components/com_storefront/admin/views/serials/tmpl/new.php
- core/components/com_storefront/admin/views/serials/tmpl/upload.php
- core/components/com_storefront/admin/views/serials/tmpl/uploadcsv.php
- core/components/com_storefront/admin/views/whitelist/tmpl/new.php
- core/components/com_storefront/site/controllers/component.php
- core/components/com_storefront/site/controllers/overview.php
- core/components/com_storefront/site/controllers/product.php
- core/components/com_storefront/site/controllers/search.php
- core/components/com_storefront/site/controllers/storefront.php
- core/components/com_storefront/site/views/browse/tmpl/collection.php
- core/components/com_storefront/site/views/search/tmpl/search.php
Also removal of some Joomla-based code.
> [fix] Stricter input casting, style fixes

- core/plugins/members/resources/resources.php
Fixes: https://nanohub.org/support/ticket/329800
> [fix] Fix ability to sort by title and popularity

- core/plugins/projects/databases/databases.php
- core/plugins/projects/feed/feed.php
- core/plugins/projects/files/connections.php
- core/plugins/projects/files/files.php
- core/plugins/projects/links/links.php
- core/plugins/projects/notes/notes.php
- core/plugins/projects/notes/views/pages/tmpl/doesnotexist.php
- core/plugins/projects/notes/views/pages/tmpl/edit.php
- core/plugins/projects/publications/publications.php
- core/plugins/projects/publications/views/draft/tmpl/review.php
- core/plugins/projects/publications/views/edititem/tmpl/default.php
- core/plugins/projects/publications/views/newversion/tmpl/default.php
- core/plugins/projects/publications/views/selector/tmpl/content.php
- core/plugins/projects/publications/views/suggestlicense/tmpl/default.php
- core/plugins/projects/team/team.php
- core/plugins/projects/todo/todo.php
- core/plugins/projects/watch/watch.php
Also changed some paths to use `Component::path()` instead of assuming `PATH_CORE`.
> [fix] Stricter input casting for project plugins

- core/components/com_resources/admin/views/imports/tmpl/display.php
Allow for single click-to-edit rather than always usig the checkbox &
toolbar combination (which was annoying me).
> [feat] Make record name clickable to edit

- core/components/com_content/api/controllers/entriesv1_0.php
- core/components/com_members/api/controllers/profilesv1_1.php
- core/components/com_members/models/member.php
- core/components/com_projects/api/controllers/projectsv1_1.php
- core/components/com_publications/api/controllers/publicationsv1_1.php
- core/components/com_publications/models/orm/publication.php
- core/components/com_publications/models/orm/version.php
- core/components/com_resources/api/controllers/entriesv1_1.php
- core/components/com_resources/models/entry.php
- core/components/com_resources/site/views/search/tmpl/solr.php
- core/components/com_search/admin/assets/js/searchable.js
- core/components/com_search/admin/controllers/searchable.php
- core/components/com_search/admin/controllers/solr.php
- core/components/com_search/admin/views/searchable/tmpl/display.php
- core/components/com_search/helpers/discoveryhelper.php
- core/components/com_search/models/solr/blacklist.php
- core/components/com_search/models/solr/filters/filter.php
- core/components/com_search/models/solr/searchcomponent.php
- core/components/com_search/site/views/solr/tmpl/_result.php
- core/plugins/search/solr/solr.php
I ensured publications and resources were properly being added
to solr without producing a duplicate.
I also ensured items added to the Blacklist would be ignored when updated,
or when the index is rebuilt.
> [fix] Ensure publications don't provide duplicate search results.

- core/components/com_projects/migrations/Migration20180807000000ComProjects.php
- core/components/com_projects/models/project.php
- core/plugins/groups/activity/views/activity/tmpl/default_item.php
Fixes: https://qubeshub.org/support/ticket/1246
> [fix] Fixes wrong scope and incorrect Project lookup

- core/plugins/members/profile/views/index/tmpl/default.php
Fixes: https://help.hubzero.org/support/ticket/11459
> [fix] Show/hide fields based on their dependencies

- core/components/com_publications/admin/views/types/tmpl/curation.php
- core/plugins/projects/publications/views/draft/tmpl/review.php
Fixes: https://qubeshub.org/support/ticket/1205
> [fix] Add check to publication request review

- core/components/com_support/admin/controllers/abusereports.php
- core/components/com_support/site/views/emails/tmpl/abuse_html.php
- core/components/com_support/site/views/emails/tmpl/abuse_plain.php
Fixes: https://nanohub.org/support/ticket/331015
> [fix] Use correct method for setting state

- core/components/com_wishlist/models/adapters/resources.php
- core/components/com_wishlist/site/controllers/wishlists.php
This also fixes an issue with getting Resource authors.
> [fix] Fixing retrieving wishlist owners for notifications

- core/plugins/groups/resources/resources.php
- core/plugins/groups/resources/views/results/tmpl/default.php
Clicking a sort option will select it. Clicking it again with change
the direction of the sort (from asc to desc, or vice versa).
Refs: https://nciphub.org/support/ticket/1481
> [feat] Allow for changing sorting direction

- core/bootstrap/Administrator/Providers/TranslationServiceProvider.php
- core/bootstrap/Site/Providers/TranslationServiceProvider.php
- core/components/com_languages/models/extension.php
- core/modules/mod_languages/helper.php
- core/plugins/system/languagefilter/languagefilter.php
This fixes a few issues with detecting and loading language based on
a URL or querystring parameter.
> [fix] Getting language switching working

- core/migrations/Migration20130702181838ComWiki.php
- core/migrations/Migration20130708082138ComWiki.php
- core/migrations/Migration20140822161100ComKb.php
- core/migrations/Migration20150326183839ComTools.php
- core/migrations/Migration20151001185523ComKb.php
- core/migrations/Migration20160325174400ComForum.php
- core/migrations/Migration20160422152647ComSupport.php
- core/migrations/Migration20160911000001ComCart.php
These are fixes to issues noticed when updating older hubs to the
latest 2.2 release.
> [fix] Making migrations a little more fault tolerant

- core/components/com_newsletter/admin/controllers/mailinglists.php
Fixes: https://nanohub.org/support/ticket/331691
> [fix] Fixing issue getting mailinglist ID

- core/components/com_storefront/admin/controllers/products.php
- core/components/com_storefront/admin/controllers/whitelist.php
- core/components/com_storefront/admin/views/products/tmpl/remove.php
Fixes: https://communityhub.purdue.edu/support/ticket/272
> [fix] Fixing deleting from whitelist and products

- core/components/com_events/admin/controllers/respondents.php
- core/components/com_events/helpers/csv.php
fixes: https://nanohub.org/support/ticket/332143
> Update /administrator respondents CSV code

- core/components/com_resources/helpers/html.php
- core/plugins/resources/about/views/index/tmpl/default.php
This makes the COiNs microformat available even if the "Cite this work"
block is disabled (the microfrmat is never visually displayed). Also
removing references to nanohub.
Refs: https://habricentral.org/support/ticket/822
> [feat][fix] COiNs available when citations disabled

- core/components/com_citations/models/citation.php
- core/components/com_citations/site/views/citations/tmpl/display.php
Fixes: https://help.hubzero.org/support/ticket/11528
> [fix] Handle cases where DB tables are ampty

- core/components/com_support/admin/controllers/tickets.php
- core/components/com_support/models/query.php
- core/components/com_support/models/ticket.php
- core/components/com_support/site/controllers/tickets.php
Fixes: https://help.hubzero.org/support/ticket/11502
> [fix] Extra guards for when there are no queries

- core/components/com_groups/models/import/record.php
- core/components/com_groups/models/orm/applicant.php
- core/components/com_groups/models/orm/group.php
- core/components/com_groups/models/orm/invitee.php
- core/components/com_groups/models/orm/manager.php
- core/components/com_groups/models/orm/member.php
This resolves some issues with adding members to a group via the
importer (and ORM models).
> [fix] Fixing issues with adding members to a group

- core/components/com_courses/admin/controllers/codes.php
- core/components/com_courses/admin/views/codes/tmpl/edit.php
- core/composer.json
- core/composer.lock
QRcode package was deprecated and was for an entirely unused feature in
the courses component. Removing feature and package.
> [maint] Removing deprecated package and unused code

- core/components/com_projects/site/assets/css/icons.css
- core/components/com_projects/site/assets/css/projects.css
Remove projects-specific presentational CSS
> [maint] Remove extra CSS specific to component

- core/composer.json
- core/composer.lock
Removing deprecated library. Replacement library will be added to the
framework, where the only code that uses it is.
> [maint] Removing deprecated library

- core/components/com_publications/admin/views/categories/tmpl/edit.php
- core/components/com_publications/models/curation.php
- core/plugins/projects/publications/assets/css/curation.css
- core/plugins/projects/publications/assets/css/publications.css
Included several commits related to fixing the style/ functionality of publications.
> Various Publication fixes

- core/plugins/publications/versions/views/browse/tmpl/default.php
> [fix] Adding scope attribute to table headers

- core/plugins/projects/files/views/connected/tmpl/_item_link.php
- core/plugins/projects/files/views/connected/tmpl/browse.php
Implemented approach results in code duplication between
_item_link.php & _item_link_file.php
Possible solution: implement & use Google file type subclass, which
would encapsulate Google-specific code (potentially large scope)
fixes: https://qubeshub.org/support/ticket/1297
> Added logic for rendering of Google file icons

- core/components/com_support/site/controllers/tickets.php
- core/modules/mod_reportproblems/tmpl/default.php
- core/plugins/captcha/image/image.php
- core/plugins/captcha/image/views/display/tmpl/default.php
- core/templates/kimera/html/mod_reportproblems/mod_reportproblems.css
Refs: https://purr.purdue.edu/support/ticket/1916
> [refactor] Support uses global captcha plugins/settings

- core/plugins/projects/notes/notes.php
Fixes: https://qubeshub.org/support/ticket/1306
> [fix] Load wiki in sub-component mode

- core/components/com_storefront/models/Product.php
Found PHP fatal errors in logs due to undelcared namespaces for
RecursiveDirectoryIterator. Added docblock where missing.
> [fix] Declaring namespaces and style fixes

- core/components/com_resources/admin/controllers/items.php
- core/components/com_resources/admin/views/items/tmpl/author.php
refs: https://pharmahub.org/support/ticket/686
> [fix] Ensure resource author role is passed to authorTask

- core/libraries/joomla/application/categories.php
Use of old Joomla constants may result in incorrect paths
> [fix] Use hubzero constants for path generation

- core/plugins/hubzero/autocompleter/autocompleter.js
Updating the language to add email
> Update members autocomleter language

- core/assets/js/gridster.js
Touch-enabled devices would cause mouse input to stop working. Upgrading
the Gridster.js library seems to resolve this issue.
Fixes: https://cdmhub.org/support/ticket/1563
> [fix] Updating lib to address drag n drop issues

- core/components/com_members/admin/controllers/imports.php
- core/components/com_resources/admin/controllers/imports.php
Fixes: https://habricentral.org/support/ticket/835
> [fix] Adding ability to sort by last run date

- core/components/com_publications/migrations/Migration20181101121435ComPublications.php
- core/components/com_publications/models/attachments/publication.php
- core/components/com_publications/tables/publication.php
- core/plugins/projects/publications/views/attachments/tmpl/publication.php
- core/plugins/projects/publications/views/selector/tmpl/content.php
Previously, selecting a publication for inclusion in a series, would
always select the most recent version. Now users can select specific
versions.
Refs: https://purr.purdue.edu/support/ticket/1965
> [feat] Select specific versions of pub for a series

- core/composer.lock
Pulls in a fix for admin toolbar popup links
Refs: https://github.com/hubzero/framework/commit/c262c8848c8daa4b72f724faecb0350613618caa
> [fix] Bumping framework

- core/components/com_storefront/admin/views/restrictions/tmpl/display.php
- core/components/com_storefront/admin/views/serials/tmpl/display.php
- core/components/com_storefront/admin/views/whitelist/tmpl/display.php
> [fix] Fix the broken popup buttons URLs

- core/components/com_dataviewer/site/lib/db.php
Fixes: https://datacenterhub.org/support/ticket/397
> [fix] Reverting input casting

- core/components/com_resources/models/import/record.php
Fixes: https://habricentral.org/support/ticket/838
> [fix] Adding missing namespace declaration

- core/components/com_members/models/registration.php
- core/components/com_members/site/views/register/tmpl/default.php
Refs: https://nanohub.org/support/ticket/335794
> [refactor] Change option from select to checkbox

- core/plugins/groups/citations/views/browse/tmpl/default.php
- core/plugins/members/citations/views/citations/tmpl/browse.php
Fixes: https://help.hubzero.org/support/ticket/11579
> [fix] Adding escaping to guard against XSS attacks

- core/components/com_groups/admin/controllers/manage.php
- core/components/com_groups/admin/views/manage/tmpl/edit.php
This adds the ability to edit the custom field data for a group via
the admin interface.
> [feat] Ability to edit custom data via admin

- core/bootstrap/Api/aliases.php
- core/components/com_projects/api/controllers/filesv1_0.php
This also fixes a minor issue with getting the correct count of file
connectors.
> [fix] Add 'Session' facade to API

- core/components/com_kb/admin/help/en-GB/articles.phtml
refs: https://qubeshub.org/support/ticket/1330
> Add documentation regarding com_kb comments

- core/components/com_blog/models/archive.php
Fixes: https://nanohub.org/support/ticket/338643
> [fix] Handle multiple state values

- core/components/com_wiki/helpers/parser.php
- core/components/com_wiki/models/book.php
- core/components/com_wiki/site/controllers/pages.php
- core/plugins/wiki/parserdefault/default/Help_Admonitions.txt
- core/plugins/wiki/parserdefault/default/Help_Includes.txt
- core/plugins/wiki/parserdefault/default/Help_Index.txt
- core/plugins/wiki/parserdefault/default/Help_PageHistory.txt
- core/plugins/wiki/parserdefault/default/Help_Processors.txt
- core/plugins/wiki/parserdefault/default/Help_Templates.txt
- core/plugins/wiki/parserdefault/default/Help_WhatIsWiki.txt
- core/plugins/wiki/parserdefault/default/Help_WikiFormatting.txt
- core/plugins/wiki/parserdefault/default/Help_WikiHtml.txt
- core/plugins/wiki/parserdefault/default/Help_WikiMacros.txt
- core/plugins/wiki/parserdefault/default/Help_WikiMath.txt
- core/plugins/wiki/parserdefault/default/Help_WikiPageNames.txt
- core/plugins/wiki/parserdefault/default/Index.txt
- core/plugins/wiki/parserdefault/default/MainPage.txt
- core/plugins/wiki/parserdefault/default/group/MainPage.txt
Since syntax and, thus, content of the default pages are dependent on
the parser being used, they should be associated with the parser.
> [feat] Move default pages to parser

- core/components/com_courses/admin/views/students/tmpl/add.php
- core/components/com_members/admin/views/quotas/tmpl/edit.php
- core/components/com_tags/admin/views/relationships/tmpl/display.php
- core/components/com_tools/admin/views/preferences/tmpl/edit.php
- core/plugins/hubzero/autocompleter/assets/css/autocompleter.css
- core/plugins/hubzero/autocompleter/assets/js/autocompleter.js
- core/plugins/hubzero/autocompleter/autocompleter.php
- core/plugins/hubzero/autocompleter/autocompleter.xml
- core/templates/kimera/html/plg_hubzero_autocompleter/autocompleter.css
Move the js and css to the assets folder to allow the some nginx servers to serve them properly
> [refactor] Move autocompleter assets to the assets folder

- core/components/com_collections/admin/controllers/posts.php
Fixes: https://qubeshub.org/support/ticket/1332
> [fix] Fixing fields that can be searched

- core/components/com_resources/models/author.php
This is supposed to fix https://help.hubzero.org/support/ticket/11623
> [fix] Get members model to get the organization

- core/components/com_projects/site/views/reports/tmpl/custom.php
- core/components/com_projects/site/views/setup/tmpl/_edit_grant_info.php
- core/components/com_projects/site/views/setup/tmpl/describe.php
- core/components/com_projects/site/views/setup/tmpl/finalize.php
- core/components/com_projects/site/views/setup/tmpl/team.php
In some cases a form action of just `index.php` can lead to some odd
routing issues.
> [fix] Routing URLs, accessibility fixes

- core/components/com_tools/migrations/Migration20181211161919ComTools.php
Refs: https://help.hubzero.org/support/ticket/11637
> [maint] Adding index for job column on joblog table

- core/libraries/joomla/JRoute.php
- core/libraries/joomla/application/application.php
Fixes: https://help.hubzero.org/support/ticket/11636
> [fix] Fixing issues with URLs not being routed

- core/components/com_projects/tables/owner.php
Fixes: https://help.hubzero.org/support/ticket/11665
> [fix] Don't `count` something that's not countable

- core/plugins/filesystem/dropbox/dropbox.php
- core/plugins/filesystem/googledrive/googledrive.php
- core/plugins/projects/files/connections.php
Redirects a user to complete the setup of a connection immediately after creating it.
> [refactor] Redirect user to oauth flow immediately

- core/components/com_resources/site/views/view/tmpl/watch.php
Fixes: https://pharmahub.org/support/ticket/690
> [fix] Make sure property exists before accessing it

- core/components/com_publications/models/orm/version.php
- core/plugins/members/publications/language/en-GB/en-GB.plg_members_publications.ini
- core/plugins/members/publications/language/en-GB/en-GB.plg_members_publications.sys.ini
- core/plugins/members/publications/migrations/Migration20181221000000PlgMembersPublications.php
- core/plugins/members/publications/publications.php
- core/plugins/members/publications/publications.xml
Refs: https://nanohub.org/support/ticket/340199
> [feat] Adding member contribution plg for publications

- core/components/com_resources/admin/controllers/items.php
Fixes: https://nanohub.org/support/ticket/339227
> [fix] Don't add all new tags as 'admin'

- core/components/com_resources/helpers/doiService.php
- core/components/com_resources/models/doi.php
- core/components/com_tools/admin/controllers/pipeline.php
- core/components/com_tools/config/config.xml
- core/components/com_tools/site/controllers/admin.php
This allows for either EZID or DataCite doi services
Fixes: https://nanohub.org/support/ticket/338817
> [refactor] Updating DOI minting for alt services

- core/plugins/groups/announcements/views/edit/tmpl/default.php
fixes: https://qubeshub.org/support/ticket/1343
> [fix] Replace anchor with span

- core/components/com_resources/migrations/Migration20180308140800ComResources.php
- core/components/com_resources/migrations/Migration20190107140800ComResources.php
- core/components/com_resources/models/doi.php
- core/components/com_resources/site/views/view/tmpl/tools.php
- core/components/com_tools/tables/version.php
- core/plugins/resources/versions/views/browse/tmpl/default.php
- core/templates/kimera/html/com_resources/view/tools.php
The DOI shoulder can change with the DOI service being used, so it
needs to be recorded along with the DOI.
Refs: https://nanohub.org/support/ticket/338817
> [fix] Add doi_shoulder column as it can change

- core/plugins/cron/publications/language/en-GB/en-GB.plg_cron_publications.ini
- core/plugins/cron/publications/publications.php
- core/plugins/cron/publications/publications.xml
Embargoed publications need to be added/removed based on
embargo date.
> [feature] add publication cron job for ftp links

- core/components/com_members/admin/controllers/members.php
- core/components/com_members/admin/language/en-GB/en-GB.com_members.members.ini
- core/components/com_members/helpers/utility.php
- core/components/com_members/site/language/en-GB/en-GB.com_members.ini
- core/components/com_members/site/views/emails/tmpl/admincreate_html.php
- core/components/com_members/site/views/emails/tmpl/approved_html.php
- core/components/com_members/site/views/emails/tmpl/approved_plain.php
- core/components/com_members/site/views/emails/tmpl/confirm.php
- core/components/com_members/site/views/emails/tmpl/confirm_html.php
- core/components/com_members/site/views/emails/tmpl/create.php
- core/components/com_members/site/views/emails/tmpl/create_html.php
- core/components/com_members/site/views/emails/tmpl/remind_html.php
- core/components/com_members/site/views/emails/tmpl/reset_html.php
Also moving text to language files, adding missing docblock.
Fixes: https://help.hubzero.org/support/ticket/11697
> [fix] Adding missing lang strings, fixing link

- core/modules/mod_eprivacy/assets/css/mod_eprivacy.css
- core/modules/mod_eprivacy/assets/js/mod_eprivacy.js
- core/modules/mod_eprivacy/composer.json
- core/modules/mod_eprivacy/helper.php
- core/modules/mod_eprivacy/index.html
- core/modules/mod_eprivacy/language/en-GB/en-GB.mod_eprivacy.ini
- core/modules/mod_eprivacy/language/en-GB/en-GB.mod_eprivacy.sys.ini
- core/modules/mod_eprivacy/migrations/Migration20190109000000ModEprivacy.php
- core/modules/mod_eprivacy/mod_eprivacy.php
- core/modules/mod_eprivacy/mod_eprivacy.xml
- core/modules/mod_eprivacy/tmpl/default.php
This has relevance to GDRP and users in the European Union
> [feat] Module for displaying cookie policy

- core/plugins/cron/resources/language/en-GB/en-GB.plg_cron_resources.ini
- core/plugins/cron/resources/resources.php
- core/plugins/cron/resources/resources.xml
- core/plugins/cron/resources/views/emails/tmpl/digest_html.php
- core/plugins/cron/resources/views/emails/tmpl/digest_plain.php
This generates a list of resoruces relevant to a user based on their
tags. Resources are given a weight based on tags and creation time to
list the freshest, most relevant items first.
> [feat] Adding task for sending relevant content emails

- core/components/com_courses/helpers/queryAddColumnStatement.php
- core/components/com_courses/helpers/queryDropColumnStatement.php
- core/components/com_courses/migrations/Migration20190102152739ComCoursesMissingColumns.php
- core/components/com_courses/models/gradebook.php
- core/components/com_courses/models/section/code.php
- core/components/com_courses/tests/queryAddColumnStatementTest.php
- core/components/com_courses/tests/queryDropColumnStatementTest.php
It seems that a migration may have gone missing for the courses
component, so I implemented a migration to add the missing columsn to
the affected tables
> [fix] Implement migration to add missing columns

- core/composer.json
- core/composer.lock
The php-jwt package was moved from the framework to help resolve some
composer dependency issues.
> [maint] Bumping framework and adding php-jwt

- core/components/com_tools/admin/controllers/pipeline.php
- core/components/com_tools/admin/controllers/versions.php
- core/components/com_tools/admin/language/en-GB/en-GB.com_tools.ini
- core/components/com_tools/admin/views/versions/tmpl/display.php
- core/components/com_tools/admin/views/versions/tmpl/edit.php
Adding a column for DOI to the list of tool versions. This also allows
for editing some of the DOI info tied to the tool version. This does
not issue DOIs, however.
> [feat] Adding DOI column and editing capability

- core/components/com_courses/admin/controllers/courses.php
Get the course ID as an array rather than the integer
> Courses copy fix

- core/composer.lock
Refs: https://github.com/hubzero/framework/commit/e04fd9697a35606d3d3c9eb43a31c881626faf03
Refs: https://github.com/hubzero/framework/commit/60ad26865eb5ece82d81c1a20e9d14d1f7a1909b
> [maint] Bumping framework

- core/plugins/projects/todo/language/en-GB/en-GB.plg_projects_todo.ini
- core/plugins/projects/todo/language/en-GB/en-GB.plg_projects_todo.sys.ini
- core/plugins/projects/todo/todo.php
- core/plugins/projects/todo/todo.xml
Fixes: https://help.hubzero.org/support/ticket/11717
> [fix] Fixing incorrect param name

- core/components/com_members/admin/views/members/tmpl/display.php
- core/components/com_members/admin/views/passwordrules/tmpl/display.php
Toolbar::confirm() doesn't exist. Need to create it?
> [fix] Reverting change

- core/components/com_search/models/solr/filters/textfieldfilter.php
The filter was returning all results from any word provided,
instead of finding the exact author.
> [fix] Ensure textfield solr filter is more precise

- core/components/com_members/site/views/emails/tmpl/confirm.php
- core/components/com_members/site/views/emails/tmpl/create.php
- core/components/com_members/site/views/emails/tmpl/create_html.php
Fixes: https://help.hubzero.org/support/ticket/11697
> [fix] Make sure link is generated correctly

- core/plugins/whatsnew/resources/resources.php
Fixes: https://nanohub.org/support/ticket/342449
> [fix] Sort records by published date first

- core/components/com_courses/site/views/form/tmpl/complete.php
Fixes: https://nanohub.org/support/ticket/343309
> [fix] Give each quesiton marker a unique ID

- core/components/com_resources/site/assets/js/hubpresenter.js
- core/components/com_resources/site/views/view/tmpl/video.php
Removing the "full screen" button as it doesn't work as expected. Maybe
reintroduce at a later point.
Refs: https://nanohub.org/support/ticket/342376
> [fix] Remove fullscreen button

- core/plugins/groups/calendar/calendar.php
Fixes: https://nciphub.org/support/ticket/1546
> [fix] Set default value appropriately

- core/modules/mod_answers/tmpl/default.php
Fixes: https://help.hubzero.org/support/ticket/11731
> [fix] Don't divide by zero

- core/plugins/members/publications/publications.php
Also removing commented out code.
Fixes: https://nanohub.org/support/ticket/343954
> [fix] Don't count entries where author='submitter'

- core/plugins/members/usage/usage.php
Fixes: https://nanohub.org/support/ticket/343841
> [fix] Display usage for items requiring login

- core/components/com_forum/models/post.php
Fixes: https://habricentral.org/support/ticket/846
> [fix] Make sure thread ID is passed to link builder

- core/plugins/projects/links/links.php
fixes: https://purr.purdue.edu/support/ticket/1995
> [fix] Allow different publications to cite source

- core/plugins/system/referrerpolicy/index.html
- core/plugins/system/referrerpolicy/language/en-GB/en-GB.plg_system_referrerpolicy.ini
- core/plugins/system/referrerpolicy/language/en-GB/en-GB.plg_system_referrerpolicy.sys.ini
- core/plugins/system/referrerpolicy/migrations/Migration20190225000000PlgSystemReferrerpolicy.php
- core/plugins/system/referrerpolicy/referrerpolicy.php
- core/plugins/system/referrerpolicy/referrerpolicy.xml
Refs: https://www.w3.org/TR/referrer-policy/
> [feat] Allow for setting Referrer Policy header

- core/plugins/projects/files/views/connected/tmpl/_item_link_file.php
fixes: https://qubeshub.org/support/ticket/1354
> [update] Allow linking to Goole forms

- core/components/com_resources/admin/assets/js/resources.js
- core/components/com_tools/admin/assets/js/handlers.js
- core/components/com_users/site/assets/js/login.js
- core/components/com_users/site/views/login/tmpl/default_login.php
- core/modules/mod_login/helper.php
- core/plugins/courses/outline/assets/js/build.js
- core/plugins/courses/outline/outline.php
- core/plugins/courses/outline/views/outline/tmpl/asset_partial.php
- core/plugins/courses/progress/assets/js/instructorprogress.js
- core/plugins/courses/progress/progress.php
- core/plugins/members/dashboard/assets/js/dashboard.admin.js
This can be done with pure CSS now and the jquery.uniform code isn't
needed anymore.
> [fix] Removing usage of Uniform

- core/components/com_blog/site/views/media/tmpl/list.php
- core/components/com_courses/admin/views/media/tmpl/list.php
- core/components/com_courses/site/views/media/tmpl/filelist.php
- core/components/com_resources/admin/assets/js/media.js
- core/components/com_resources/admin/views/media/tmpl/list.php
- core/components/com_resources/site/views/media/tmpl/display.php
- core/components/com_tools/site/views/media/tmpl/display.php
- core/components/com_tools/site/views/storage/tmpl/filelist.php
- core/components/com_wiki/site/views/media/tmpl/list.php
- core/plugins/courses/pages/views/pages/tmpl/list.php
Also, making sure needed JS libraries are loaded.
> [fix] Putting back some needed targets

- core/components/com_members/site/views/emails/tmpl/confirm.php
refs: https://nanohub.org/support/ticket/343973
> [refactor] Account confirmation email view

- core/components/com_wiki/models/version.php
- core/components/com_wiki/site/views/special/tmpl/links.php
Slightly improved query for gettign links to a wiki page
> [fix] Enable link logging

- core/components/com_dataviewer/site/html/spreadsheet.js
fixes: https://purr.purdue.edu/support/ticket/1997
> [fix] Update datatable config to fix search inputs

- core/composer.lock
Refs: https://github.com/hubzero/framework/commit/e04fd9697a35606d3d3c9eb43a31c881626faf03
Refs: https://github.com/hubzero/framework/commit/60ad26865eb5ece82d81c1a20e9d14d1f7a1909b
Refs: https://github.com/hubzero/framework/commit/ade7a7ee45c78d27e7c072efdc1033a2afed28b8
Refs: https://github.com/hubzero/framework/commit/f92eb7652720e9ef9f524b1bef40d4c2cad2b609
Refs: https://github.com/hubzero/framework/commit/8625506409b841431070ec2bc33906865a0e6412
Refs: https://github.com/hubzero/framework/commit/6c3a76b2a05187e25ae3c4e1309f937d9eaa88b5
Refs: https://github.com/hubzero/framework/commit/a05eaecfc3c696731103120089a7f1687433dcbe
Refs: https://github.com/hubzero/framework/commit/d592acedf9d5fd4631182af90843a0ce4b6cf201
Refs: https://github.com/hubzero/framework/commit/a2a8de068bdebf62963054 …
> [maint] Bumping framework.

- core/components/com_menus/admin/assets/js/menus.js
- core/components/com_menus/admin/controllers/items.php
- core/components/com_menus/models/module.php
Also a SQL fix for MySQL strict mode.
Fixes: https://qubeshub.org/support/ticket/1378
Fixes: https://nanohub.org/support/ticket/344849
> [fix] Fixing issues with saving menu items

- core/migrations/Migration20160208183103ComFeedaggregator.php
> [fix] Perform queries with raw SQL, not models

- core/components/com_courses/migrations/Migration20190228114147ComCourses.php
- core/components/com_tools/migrations/Migration20190228114147ComTools.php
- core/migrations/Migration20141201170547ComGroups.php
- core/migrations/Migration20160328133847ComCitations.php
- core/migrations/Migration20161213132518PlgSearchSolr.php
- core/migrations/Migration20170117114147ComProjects.php
- core/migrations/Migration20170124114147ComGroups.php
- core/migrations/Migration20170124175120ComBillboards.php
- core/migrations/Migration20170124191209ComCitations.php
- core/migrations/Migration20170129140423PlgXmessage.php
- core/migrations/Migration20170201125723ComPublications.php
- core/migrations/Migration20170209150806ComSupport.php
- core/migrations/Migration20170220190109ComTime.php
- core/migrations/Migration20170731201800ComResources.php
- core/migrations/Migration20170913133847Core.php
- core/migrations/Migration20170921114147ComMembers.php
- core/migrations/Migration20170921120323ComMembers.php
- core/migrations/Migration20190228114147MediaTracking.php
- core/plugins/search/solr/migrations/Migration20170831000000PlgSearchSolr.php
- core/plugins/search/solr/solr.php
Fixes issues with:
* A SOLR search database table being accessed on event calls before
it had been created.
* SQL that didn't conform to MySQL strict mode standards.
Fixes: https://help.hubzero.org/support/ticket/11752
> [fix] Fixing issues with migrations

- core/plugins/geocode/local/LocalProvider.php
Apparently if was in existence for quite a while... Adding to the list.
> [fix] Add South Sudan to the list of the countries

- core/modules/mod_adminmenu/tmpl/default_disabled.php
- core/modules/mod_adminmenu/tmpl/default_enabled.php
- core/modules/mod_adminmenu/tree.php
This allows for more/easier styling.
> [feat] Adding classes and marking active items

- core/components/com_modules/admin/assets/js/modules.js
- core/components/com_modules/models/module.php
Also fixes JS issue with admin toolbar buttons not working in the module
list view.
Fixes: https://qubeshub.org/support/ticket/1380
Fixes: https://qubeshub.org/support/ticket/1379
> [fix] Fixing issue with publish_up/down times

- core/components/com_wishlist/admin/views/comments/tmpl/edit.php
- core/components/com_wishlist/admin/views/lists/tmpl/edit.php
- core/components/com_wishlist/admin/views/wishes/tmpl/edit.php
- core/components/com_wishlist/models/wishlist.php
Also minor fixes to remove unneeded buttons and fixing issue with edit
list view where a (magic) method was being called instead of a property.
> [fix] Fixing issue with creating list via admin

- core/bootstrap/Install/sql/mysql/hubzero.sql
- core/components/com_newsletter/migrations/Migration20170902000000ComNewsletter.php
- core/migrations/Migration20190305000000HgUpdateQueue.php
- core/migrations/Migration20190305000000Sites.php
- core/plugins/cron/groups/migrations/Migration20170902000000PlgCronGroups.php
- core/plugins/cron/newsletter/migrations/Migration20170902000000PlgCronNewsletter.php
Also moving some default install content to migrations in related
extensions.
> [fix] Removing refs to deprecated tables

- core/plugins/user/autoapprove/autoapprove.php
Fixes: https://socialmediamacroscope.org/support/ticket/59
> [fix] Check for array index before accessing it

- core/plugins/members/profile/views/index/tmpl/default.php
Fixes: https://qubeshub.org/support/ticket/1381
> [fix] Set `text` property before passing to event

- core/components/com_activity/migrations/Migration20190221000000ComActivity.php
- core/components/com_activity/migrations/Migration20190305000000ComActivity.php
- core/components/com_collections/migrations/Migration20190305000000ComCollections.php
- core/components/com_groups/migrations/Migration20170831000000ComGroups.php
- core/components/com_groups/migrations/Migration20170901000000ComGroups.php
- core/components/com_groups/migrations/Migration20190221000000ComGroups.php
- core/components/com_groups/models/orm/field.php
- core/components/com_installer/migrations/Migration20170831000000ComInstaller.php
- core/components/com_media/migrations/Migration20170831000000ComMedia.php
- core/components/com_members/migrations/Migration20170831000000ComMembers.php
- core/components/com_messages/migrations/Migration20170831000000ComMessages.php
- core/components/com_modules/migrations/Migration20170831000000ComModules.php
- core/components/com_support/admin/views/tickets/tmpl/display.php
- core/components/com_support/migrations/Migration20190305000000ComSupport.php
- core/components/com_support/site/views/tickets/tmpl/display.php
- core/modules/mod_adminmenu/migrations/Migration20190306000000ModAdminmenu.php
- core/plugins/antispam/bayesian/migrations/Migration20170901000000PlgAntispamBayesian.php
- core/plugins/antispam/bayesian/migrations/Migration20190305000000PlgAntispamBayesian.php
- core/plugins/groups/activity/activity.php
- core/plugins/members/activity/activity.php
Fixes some components' install migration adding an admin menu entry when it shouldn't, fixes some typos, and converts a few more datetime fields for MySQL strict mode acceptance.
> Various migration fixes

- core/components/com_groups/admin/assets/js/groups.js
- core/components/com_groups/admin/assets/js/membership.js
- core/components/com_groups/admin/views/membership/tmpl/display.php
- core/components/com_groups/admin/views/membership/tmpl/new.php
Fixes: https://help.hubzero.org/support/ticket/11763
> [fix] Fixing file inclusion issues

- core/components/com_installer/admin/controllers/packages.php
- core/components/com_installer/admin/controllers/repositories.php
- core/components/com_installer/admin/views/packages/tmpl/add.php
- core/components/com_installer/admin/views/packages/tmpl/edit.php
- core/components/com_installer/admin/views/repositories/tmpl/edit.php
Try to catch Composer config errors and return the messages a little
nicer. Also, fixes a couple minor issues with cancel buttons.
> [fix] Catch errors, minor styling clean-up

- core/bootstrap/start.php
PHP gets very angry if this isn't set.
> [fix] Set PHP default timezone

- core/components/com_answers/admin/views/answers/tmpl/edit.php
- core/components/com_answers/admin/views/questions/tmpl/edit.php
- core/components/com_citations/admin/views/citations/tmpl/edit.php
- core/components/com_collections/admin/views/collections/tmpl/edit.php
- core/components/com_resources/admin/views/items/tmpl/edit.php
- core/components/com_tags/admin/views/entries/tmpl/edit.php
Minor HTML reworking of Resources custom fields to fix some style
issues.
> [fix] Removing editor buttons where not needed

- core/plugins/projects/databases/databases.php
Removing references to Joomla code and changing `print` to `echo` as
it's slightly more efficient.
> [fix] Use Hubzero database driver

- core/components/com_activity/admin/controllers/entries.php
- core/components/com_activity/admin/views/entries/tmpl/display.php
Also fixes an issue with loading dates.
> [fix] Fixing chart loading when total is zero

- core/components/com_services/models/service.php
Fixes: https://nanohub.org/support/ticket/336222
> [fix] Fixing query to match what it was before refactor

- core/components/com_checkin/models/inspector.php
- core/components/com_publications/admin/views/items/tmpl/display.php
Also fixing an issue with marking checkedout publications as such.
> [fix] Fixing issues with checking in tables

- core/components/com_wiki/site/controllers/history.php
- core/components/com_wiki/site/controllers/pages.php
- core/plugins/groups/wiki/wiki.php
Also moves methods to a more appropriate controller.
> [refactor] Guard against query tampering

- core/components/com_forum/models/post.php
Fixes: https://catalyzecare.org/support/ticket/672
> [fix] Update record if thread ID is missing

- core/components/com_login/site/assets/css/factors.css
- core/components/com_login/site/assets/css/link.css
- core/components/com_login/site/assets/css/login.css
- core/components/com_login/site/assets/css/providers.css
- core/components/com_login/site/assets/css/userconsent.css
- core/components/com_login/site/assets/css/users.css
- core/components/com_login/site/assets/js/link.js
- core/components/com_login/site/assets/js/login.js
- core/components/com_login/site/controllers/auth.php
- core/components/com_login/site/language/en-GB/en-GB.com_login.ini
- core/components/com_login/site/login.php
- core/components/com_login/site/router.php
- core/components/com_login/site/views/endsinglesignon/tmpl/default.php
- core/components/com_login/site/views/factors/tmpl/default.php
- core/components/com_login/site/views/link/tmpl/default.php
- core/components/com_login/site/views/login/index.html
- core/components/com_login/site/views/login/tmpl/default.php
- core/components/com_login/site/views/login/tmpl/default.xml
- core/components/com_login/site/views/login/tmpl/default_login.php
- core/components/com_login/site/views/login/tmpl/default_logout.php
- core/components/com_login/site/views/login/tmpl/index.html
- core/components/com_login/site/views/logout/tmpl/default.php
- core/components/com_login/site/views/logout/tmpl/default.xml
- core/components/com_login/site/views/userconsent/tmpl/default.php
This still requires all other extensions and menu items point to it.
> [refactor] Initi copy of login code from com_users

- core/plugins/cron/resources/resources.php
The limit was for testing. Bad on me for leaving it in there.
> [fix] Removing user ID limitation

- core/components/com_members/site/controllers/profiles.php
- core/components/com_members/site/language/en-GB/en-GB.com_members.ini
- core/components/com_members/site/router.php
- core/components/com_members/site/views/profiles/tmpl/spamjail.php
- core/components/com_members/site/views/profiles/tmpl/unapproved.php
Copying the spamjail and unapproved views form com_users as the
component is to be deprecated soon.
> [feat] Copying views from com_users

- core/plugins/content/externalhref/externalhref.php
- core/plugins/content/externalhref/externalhref.xml
- core/plugins/content/externalhref/index.html
- core/plugins/content/externalhref/language/en-GB/en-GB.plg_content_externalhref.ini
- core/plugins/content/externalhref/language/en-GB/en-GB.plg_content_externalhref.sys.ini
- core/plugins/content/externalhref/migrations/Migration20190319000000PlgContentExternalhref.php
Refs: https://nanohub.org/support/ticket/345585
> [feat] Plugin to force nofollow attr on external links

- core/components/com_groups/admin/controllers/pages.php
- core/components/com_groups/admin/views/pages/tmpl/edit.php
Refs: https://help.hubzero.org/support/ticket/11779
> [feat] Admin group page form uses site editor

- core/components/com_publications/admin/controllers/items.php
Private publications were explicitly excluded from listing on admin
panel
> [fix] Show all publications in admin view

- core/plugins/groups/collections/collections.php
- core/plugins/members/collections/collections.php
Fixes: https://help.hubzero.org/support/ticket/11784
> [fix] Adding missing line that saves tags

- core/bootstrap/Cli/shim.php
* Removing Jomla specific code (it's set in the Joomla service provider
anyway.
* Set PHP's default timezone or else PHP gets cranky
* Check for additional services in `/app`
> [fix] Remove Joomla ref, check for services in app

- core/components/com_projects/migrations/Migration20170902000000ComProjects.php
- core/components/com_publications/migrations/Migration20170902000000ComPublications.php
Adding a couple missing migrations for installing the default content.
> [feat] Adding migrations for default content

- core/components/com_menus/migrations/Migration20170901000000ComMenus.php
- core/migrations/Migration20190321000000Core.php
This allows the database to be run in strict mode.
> [maint] Changing default value for datetime fields

- core/components/com_resources/site/views/view/tmpl/tools.php
- core/templates/kimera/html/com_resources/view/tools.php
Refs: https://nanohub.org/support/ticket/345738
> [fix] Fixing showing open source download

- core/components/com_courses/site/assets/js/courses.overview.js
- core/components/com_courses/site/controllers/course.php
* Fix issue with updating course image
* Fix issue with redirecting to new, copied course after copying
> [fix] Fixing issue with updating img, redirect

- core/components/com_redirect/admin/assets/js/redirect.js
- core/components/com_redirect/admin/views/links/tmpl/edit.php
Removing a stray character from the JS file and removing 'required' from
a field that should be optional.
> [fix] Removing stray character, make field optional

- core/components/com_login/models/login.php
Fixes some cases where the redirect after logout won't go to the correct
path (e.g., /administrator).
> [fix] Fixes some potentially rare redirect issues

- core/components/com_config/models/forms/application.xml
Refs: https://github.com/hubzero/framework/commit/2650ee3dfe97cfe0e9fd479ab4a07dbcf125c7ce
> [feat] Adding Percona to database driver list

- core/components/com_storefront/admin/views/collections/tmpl/edit.php
Fixes: https://communityhub.purdue.edu/support/ticket/284
> [fix] Include core scripts

- .travis.yml
- core/bin/php_tests.sh
Adds PHP syntax checking to the linter and more robust rejection of
non-PHP files to the code sniffer
> [feat] Update travis build

- core/components/com_members/api/controllers/toolsv1_0.php
- core/components/com_tools/api/controllers/sessionsv1_0.php
- core/modules/mod_mysessions/helper.php
This adds an extra guard against accounts created with 3rd-party
authenticators that haven't compelted the authentication process.
Fixes: https://help.hubzero.org/support/ticket/11798
> [fix] Ensure user is a valid account

- core/components/com_groups/admin/controllers/pages.php
Also, a couple minor changes for inserted values for MySQL strict mode.
Fixes: https://help.hubzero.org/support/ticket/11778
> [fix] Fixing nested set when new records are added

- .travis.yml
Saves a for loop that checks if the files were deleted or not - silly
because git already would have known that information.
> [fix] Don't have git report deleted files

- core/plugins/projects/links/links.php
fixes: https://purr.purdue.edu/support/ticket/2010
> [fix] Ensure citation journal datum is a string

- core/assets/js/hubzero.js
This tries to determine the hub's root install path. Fixes URLs for
hubs that might have an unusual setup such as being in a sub-directory
of the server's web root.
> [fix] Determine root path

- core/components/com_courses/migrations/Migration20190404000000ComCourses.php
- core/components/com_courses/models/course.php
- core/components/com_courses/site/assets/css/course.css
- core/components/com_courses/site/assets/css/courses.css
- core/components/com_courses/site/controllers/course.php
- core/components/com_courses/site/language/en-GB/en-GB.com_courses.ini
- core/components/com_courses/site/router.php
- core/components/com_courses/site/views/course/tmpl/delete.php
- core/components/com_courses/site/views/course/tmpl/display.php
- core/components/com_courses/site/views/course/tmpl/edit.php
- core/components/com_courses/site/views/course/tmpl/fork.php
A fork is a copy of a course but ownership & managment of the course
changes to whomever creted the fork.
Also, fixed a couple bugs and added some Bootstrap class names to form
elements.
> [feat] Adding ability to fork courses

- core/components/com_menus/admin/controllers/items.php
- core/components/com_menus/models/item.php
Also fixing an issue with not properly clearing session data.
> [fix] Propogate alias change to child paths

- core/components/com_languages/admin/controllers/overrides.php
- core/components/com_languages/models/override.php
Refs: https://qubeshub.org/support/ticket/1397
> [fix] Language IDs are strings

- core/components/com_installer/admin/views/packages/tmpl/edit.php
Refs: https://qubeshub.org/support/ticket/1400
> [fix] Make sure var is set before using it

- core/plugins/projects/team/views/quit/tmpl/default.php
fixes: https://qubeshub.org/support/ticket/1404
> [fix] Allow user to quit project if not synced with group

- core/plugins/members/dashboard/assets/css/dashboard.css
- core/plugins/members/dashboard/assets/js/dashboard.js
- core/plugins/members/dashboard/views/display/tmpl/default.php
Adding a wrapper around the main modules workspace allows for adusting
margins and padding on the plugin_content area without affecting the
modules.
> [refactor] Add module container

- core/components/com_config/admin/controllers/application.php
- core/components/com_config/admin/language/en-GB/en-GB.com_config.ini
- core/components/com_config/admin/views/application/tmpl/default.php
- core/components/com_config/admin/views/application/tmpl/default_other.php
This will read any extra config files and display basic text inputs
so they values can be adjusted and preserved upon save.
> [feat] Display edit fields for extra config files

- core/components/com_support/site/language/en-GB/en-GB.com_support.ini
- core/components/com_support/site/views/abuse/tmpl/display.php
- core/components/com_support/site/views/tickets/tmpl/new.php
- core/components/com_support/site/views/tickets/tmpl/stats.php
- core/components/com_support/site/views/tickets/tmpl/ticket.php
- core/components/com_wishlist/models/attachment.php
- core/components/com_wishlist/site/views/wishlists/tmpl/_comment.php
- core/components/com_wishlist/site/views/wishlists/tmpl/editwish.php
- core/components/com_wishlist/site/views/wishlists/tmpl/settings.php
- core/components/com_wishlist/site/views/wishlists/tmpl/wish.php
Adding more Bootstrap class names to form elements and some
accessibility fixes while muckin' about.
> [fix][feat] Bootstrap classes, accessibility fixes

- core/plugins/authentication/certificate/certificate.php
- core/plugins/authentication/certificate/language/en-GB/en-GB.plg_authentication_certificate.ini
- core/plugins/authentication/facebook/facebook.php
- core/plugins/authentication/facebook/language/en-GB/en-GB.plg_authentication_facebook.ini
- core/plugins/authentication/google/google.php
- core/plugins/authentication/google/language/en-GB/en-GB.plg_authentication_google.ini
- core/plugins/authentication/linkedin/language/en-GB/en-GB.plg_authentication_linkedin.ini
- core/plugins/authentication/linkedin/linkedin.php
- core/plugins/authentication/orcid/language/en-GB/en-GB.plg_authentication_orcid.ini
- core/plugins/authentication/orcid/orcid.php
- core/plugins/authentication/pucas/language/en-GB/en-GB.plg_authentication_pucas.ini
- core/plugins/authentication/pucas/pucas.php
- core/plugins/authentication/twitter/language/en-GB/en-GB.plg_authentication_twitter.ini
- core/plugins/authentication/twitter/twitter.php
https://qubeshub.org/support/ticket/1408
> [fix] Adding language strings

- core/components/com_projects/models/orm/project.php
Refs: https://mygeohub.org/support/ticket/1393
> [fix] Adding missing method

- core/components/com_projects/site/assets/js/setup.js
- core/components/com_projects/site/language/en-GB/en-GB.com_projects.ini
- core/components/com_projects/site/views/projects/tmpl/_header.php
- core/components/com_projects/site/views/setup/tmpl/_edit_grant_info.php
- core/components/com_projects/site/views/setup/tmpl/_edit_info.php
- core/components/com_projects/site/views/setup/tmpl/_picture.php
- core/components/com_projects/site/views/setup/tmpl/_sections.php
- core/components/com_projects/site/views/setup/tmpl/_steps.php
- core/components/com_projects/site/views/setup/tmpl/describe.php
- core/components/com_projects/site/views/setup/tmpl/edit.php
- core/components/com_projects/site/views/setup/tmpl/finalize.php
- core/components/com_projects/site/views/setup/tmpl/team.php
- core/templates/kimera/html/com_projects/setup/edit.php
* Adding missing `for` attribute on labels
* Javascript fixes for jQuery upgrade (use `prop()` instead of `attr()`
for testing if a checkbox or radio is selected)
* Some reformatting of views to for easier reading
* Reducing duplicated code
* Adding Bootstrap classes to form elements
> [fix] Accessibility, code reduction, bug fixes

- core/components/com_cart/lib/auditors/Membership_Auditor.php
- core/components/com_cart/lib/auditors/Software_Auditor.php
- core/components/com_cart/models/CurrentCart.php
- core/components/com_cart/site/controllers/checkout.php
- core/components/com_cart/site/controllers/download.php
- core/components/com_categories/helpers/node.php
- core/components/com_languages/admin/controllers/languages.php
- core/components/com_login/site/controllers/auth.php
- core/components/com_members/site/controllers/credentials.php
- core/components/com_menus/models/item.php
- core/components/com_oauth/api/controllers/api.php
- core/components/com_search/admin/controllers/solr.php
- core/components/com_tools/models/middleware.php
- core/components/com_tools/site/controllers/resources.php
- core/migrations/Migration20130924000002Core.php
- core/migrations/Migration20130924000009ComMenus.php
- core/migrations/Migration20150330124145Core.php
- core/plugins/authentication/google/google.php
- core/plugins/authentication/linkedin/linkedin.php
- core/plugins/members/account/account.php
- core/plugins/members/contributions/views/display/tmpl/default.php
- core/plugins/projects/files/files.php
- core/plugins/publications/reviews/models/review.php
- core/plugins/system/debug/debug.php
- core/plugins/system/languagefilter/languagefilter.php
In some cases, variables were renamed to avoid polluting searches for
Joomla references.
> [fix] Removing Joomla references

- core/components/com_content/admin/assets/js/content.js
Fixes: https://qubeshub.org/support/ticket/1409
> [fix] Add support for submitbutton on listing page

- core/components/com_resources/admin/views/items/tmpl/edit.php
This option seems to cause trouble as people uncheck it without knowing
what they're doing. Best to hide it.
Fixes: https://nanohub.org/support/ticket/348113
> [fix] Changing input to hidden field

- core/components/com_projects/site/controllers/base.php
Previous functionality would pass messages to the view and output them
with its own redundant functionality.
> [refactor] Use standard notification system

- core/components/com_projects/models/repo.php
Refs: https://help.hubzero.org/support/ticket/11593
> [fix] Remove problematic chars from dir names

- core/components/com_publications/admin/views/items/tmpl/_selectcontent.php
Instead, display list of files for the publication.
Fixes: https://purr.purdue.edu/support/ticket/2027
> [fix] Don't auto-create bundle

- core/plugins/authentication/facebook/facebook.php
Fixes: https://stemedhub.org/support/ticket/614
> [fix] Adding missing 't'

- core/components/com_tools/site/controllers/pipeline.php
Fixes: https://vhub.org/support/ticket/1908
> [fix] Make sure index is set before attempted use

- core/components/com_newsletter/site/assets/js/newsletter.js
Fixes: https://qubeshub.org/support/ticket/1413
> [fix] Fixed iframe jquery issue

- core/components/com_support/site/assets/js/support.js
Fixes: https://nanohub.org/support/ticket/349485
> [fix] Use `prop` instead of `attr`

- core/components/com_projects/api/controllers/projectsv2_0.php
- core/components/com_projects/models/orm/owner.php
- core/components/com_projects/models/orm/project.php
Fixes: https://help.hubzero.org/support/ticket/11815
> [fix] Create & sync system group

- core/modules/mod_adminlogin/assets/css/login.css
- core/modules/mod_adminlogin/tmpl/default.php
Syncing changes in authenticator styles from front-end login to admin
login.
> [fix] Update authenitcator CSS for admin login

- core/components/com_groups/site/controllers/membership.php
This fixes issues with variance in capitalization and equality checks.
Fixes: https://nciphub.org/support/ticket/1584
> [fix] Force emails to lowercase

- core/plugins/content/formathtml/macros/group/announcements.php
Refs: https://stemedhub.org/support/ticket/616
> [feat] Adding group announcements maco

- core/components/com_modules/admin/controllers/modules.php
MySQL strict mode complains otherwise
> [fix] Make sure content has a value

- core/components/com_categories/admin/controllers/categories.php
- core/components/com_categories/admin/views/categories/tmpl/edit.php
- core/components/com_categories/models/category.php
Fixes: https://help.hubzero.org/support/ticket/11821
> [fix] Add missing methods for setting path

- core/components/com_tools/helpers/html.php
Fixes: https://nanohub.org/support/ticket/349656
> [fix] Can't have two `class` attributes

- core/plugins/projects/files/files.php
- core/plugins/projects/files/views/selector/tmpl/default_selectform.php
Fixes: https://purr.purdue.edu/support/ticket/2035
> [fix] Adding block to retrieve initial file list

- core/components/com_resources/helpers/html.php
- core/plugins/resources/about/views/index/tmpl/default.php
- core/plugins/resources/coins/coins.php
- core/plugins/resources/coins/coins.xml
- core/plugins/resources/coins/language/en-GB/en-GB.plg_resources_coins.ini
- core/plugins/resources/coins/language/en-GB/en-GB.plg_resources_coins.sys.ini
- core/plugins/resources/coins/migrations/Migration20170831000000PlgResourcesCoins.php
Refs: https://habricentral.org/support/ticket/852
> [refactor] Moving COinS microformat to plugin

- core/components/com_projects/helpers/githelper.php
- core/components/com_projects/helpers/nogithelper.php
- core/components/com_projects/models/adapters/git.php
- core/components/com_projects/models/adapters/nogit.php
- core/plugins/projects/files/files.php
Fixes: https://purr.purdue.edu/support/ticket/2034
> [fix] Recursively list directories to move file

- core/components/com_kb/site/views/articles/tmpl/article.php
- core/components/com_wishlist/models/wishlist.php
- core/modules/mod_menu/helper.php
- core/modules/mod_mytickets/tmpl/default.php
Slight reworking of ieyasu's suggested fixes. This addresses a couple other issues found along the way.
> 2.2 ieyasu fixes

- core/plugins/projects/files/files.php
Might have been an incorrect action listed (submit)
Fixes: https://qubeshub.org/support/ticket/1420
> [fix] Can now select img for pub outside project

- core/components/com_publications/admin/assets/js/publications.js
- core/components/com_publications/admin/views/items/tmpl/display.php
- core/components/com_publications/admin/views/items/tmpl/edit.php
Some pages were missing framework or included in wrong order. Also fixes
some JS syntax errors.
Fixes: https://purr.purdue.edu/support/ticket/2033
> [fix] Get admin interface working

- core/components/com_menus/models/item.php
This fixes some issues with MySQL strict mode
> [fix] Ensure field has a default value

- core/components/com_support/models/comment.php
This prevents the original comment from being overwritten by the parsed
version.
> [fix] Store parsed comment in alternate attribute

- core/assets/less/comments.less
- core/components/com_answers/site/views/questions/tmpl/search.php
- core/components/com_kb/site/views/articles/tmpl/article.php
- core/components/com_poll/site/views/polls/tmpl/display.php
- core/components/com_publications/site/views/browse/tmpl/default.php
- core/templates/kimera/less/_comments.less
Fixes: https://nciphub.org/support/ticket/1590
> [fix] Fixes to improve accessibility

- core/components/com_citations/helpers/format.php
- core/components/com_citations/models/citation.php
DOIs are effectively URLs, so it makes sense to link them.
Refs: https://purr.purdue.edu/support/ticket/2044
> [feat] Link DOIs

- core/components/com_support/site/assets/css/conditions.css
- core/components/com_support/site/assets/js/condition.builder.js
- core/components/com_support/site/assets/js/tickets.js
This was attempting to load necessary conditions data before it was
available. Also some minor style fixes.
Fixes: https://qubeshub.org/support/ticket/1430
> [fix] Load data when available

- core/components/com_citations/helpers/format.php
- core/components/com_citations/models/citation.php
Fixes: https://qubeshub.org/support/ticket/1431
> [fix] Make sure property exists

- core/components/com_login/site/controllers/auth.php
Not entirely sure what would cause this yet.
> [fix] Make sure logout doesn't redirect to self

- core/components/com_login/site/assets/css/link.css
- core/components/com_users/site/assets/css/link.css
- core/plugins/authentication/pucas/assets/css/pucas.css
Adds a missing class and removes pseudo generated content for PUCAS
authenticator.
> [fix] Adjusting some styles

- core/plugins/oaipmh/publications/data/miner.php
Refs: https://purr.purdue.edu/support/ticket/2048
> [fix] Only retrieve authors with status=1

- core/components/com_members/models/profile/field.php
Fixes: https://hubicl.org/support/ticket/123
> [fix] Add default selected value info to options

- core/plugins/courses/outline/outline.php
- core/plugins/courses/pages/pages.php
- core/plugins/groups/forum/forum.php
- core/plugins/members/account/account.php
- core/plugins/members/messages/messages.php
Refs: https://help.hubzero.org/support/ticket/11843
> [refactor] Removing usage of deprecated methods

- core/modules/mod_incremental_registration/tmpl/popover.php
Fixes: https://nanohub.org/support/ticket/350971
> [fix] Fix empty selects, 404s on POST

- core/components/com_projects/admin/views/team/tmpl/new.php
Fixes: https://purr.purdue.edu/support/ticket/2054
> [fix] Adding missing quotes

- core/components/com_projects/site/controllers/projects.php
- core/components/com_projects/tables/owner.php
It's possible to have email addresses with varying case.
Fixes: https://purr.purdue.edu/support/ticket/2053
> [fix] Force all lowercase when doing a lookup

- core/components/com_search/models/basic/result/assoclist.php
- core/components/com_search/models/basic/result/sql.php
- core/plugins/search/members/members.php
This is a follow-up to a change that checks if the returned var is
countbale or not.
Refs: https://github.com/hubzero/hubzero-cms/pull/1115
> [refactor] Implement `Countable` interface

- core/components/com_courses/migrations/Migration20190228114147ComCourses.php
Check that the table has the field it wasn't to make an index for.
> [fix] Check that the field exists first

- core/components/com_projects/site/controllers/projects.php
- core/components/com_projects/site/views/projects/tmpl/external.php
fixes: https://purr.purdue.edu/support/ticket/2049
> [refactor] Allow former members to request access

- core/components/com_collections/site/views/posts/tmpl/display_file.php
- core/components/com_collections/site/views/posts/tmpl/display_link.php
- core/plugins/groups/collections/views/post/tmpl/default_file.php
- core/plugins/groups/collections/views/post/tmpl/default_link.php
- core/plugins/members/collections/views/post/tmpl/default_file.php
- core/plugins/members/collections/views/post/tmpl/default_link.php
Fixes: https://nciphub.org/support/ticket/1602
> [fix] Add `noreferrer` to external links

- core/modules/mod_rapid_contact/assets/css/mod_rapid_contact.css
- core/modules/mod_rapid_contact/tmpl/default.php
Also a minor accessibility fix for fieldset legends
> [feat] Adding Bootstrap class names

- core/components/com_publications/models/orm/publication.php
- core/components/com_publications/models/publication.php
- core/components/com_publications/site/assets/css/filelist.css
- core/components/com_publications/site/assets/css/publications.css
- core/components/com_publications/site/controllers/publications.php
- core/templates/kimera/html/com_publications/publications.css
Adds state constants to models so it's easier to reference what a state
value means
> [refactor] More clean-up, refactoring

- core/components/com_newsletter/models/newsletter.php
fixes: https://qubeshub.org/support/ticket/1441
> Strip script tags from newsletter preview content

- core/components/com_installer/admin/assets/js/installer.js
- core/components/com_installer/admin/controllers/packages.php
- core/components/com_installer/admin/controllers/repositories.php
- core/components/com_installer/admin/views/manage/tmpl/default.php
- core/components/com_installer/admin/views/packages/tmpl/add.php
- core/components/com_installer/admin/views/packages/tmpl/display.php
- core/components/com_installer/admin/views/packages/tmpl/edit.php
- core/components/com_installer/admin/views/repositories/tmpl/display.php
- core/components/com_installer/admin/views/repositories/tmpl/edit.php
Added after delete events, more access checks, better accessibility,
and some minor reformatting.
> [refactor] Moving JS to external file

- core/components/com_config/models/application.php
Refs: https://help.hubzero.org/support/ticket/11852
> [fix] Handle cases where array indices are undefined

- core/components/com_publications/helpers/tags.php
- core/components/com_publications/migrations/Migration20190620000000ComPublications.php
- core/components/com_publications/models/blocks/tags.php
- core/components/com_publications/models/orm/publication.php
- core/components/com_publications/models/orm/version.php
- core/components/com_publications/models/publication.php
This moves tags from the publication as a whole to each version of
the publication.
> [feat] Associate tags with versions

- core/components/com_system/api/controllers/systemv1_0.php
TODO: Re-evaluate information provided by this endpoint.
> [fix] Removing unneeded items throwing errors

- core/bootstrap/Site/routes.php
- core/components/com_tags/site/controllers/tags.php
Refs: https://github.com/hubzero/framework/pull/594
Fixes: https://help.hubzero.org/support/ticket/11858
> [fix] Typecaset incoming values

- core/modules/mod_twitterfeed/assets/js/mod_twitterfeed.js
- core/modules/mod_twitterfeed/tmpl/default.php
Refs: https://twittercommunity.com/t/deprecating-widget-settings/102295
> [fix] Updating for changes in Twitter's embed code

- core/components/com_citations/admin/controllers/citations.php
- core/components/com_citations/admin/views/citations/tmpl/edit.php
- core/components/com_publications/models/doi.php
- core/migrations/Migration20190325155621PlgCitationDoi.php
- core/plugins/citation/doi/doi.php
- core/plugins/citation/doi/doi.xml
- core/plugins/citation/doi/language/en-GB/en-GB.plg_citation_doi.ini
- core/plugins/citation/doi/language/en-GB/en-GB.plg_citation_doi.sys.ini
The changes include:
1. Create a doi plugin of citation component for pushing the citation to the corresponding DOI's metadata record on DataCite.
2. Correct the option values of the context field on citation component admin interface. 
3. Change the DOI registration http request method from "PUT" to "POST", which conforms to the DataCite MDS API standard.
The details can be found on PURR ticket #2009
> [PURR][#2009] Include citation information of dataset in DOI metadata record

- core/components/com_installer/admin/views/packages/tmpl/add.php
- core/components/com_installer/admin/views/packages/tmpl/edit.php
Fixes: https://qubeshub.org/support/ticket/1450
> [fix] Fixing incorrect arguments list

- core/components/com_publications/admin/controllers/items.php
Fixes: https://purr.purdue.edu/support/ticket/2059
> [fix] Use version ID instead of publication ID

- core/components/com_publications/migrations/Migration20190620000000ComPublications.php
Fixes: https://purr.purdue.edu/support/ticket/2062
> [fix] Reworking migration to handle edge cases

- core/components/com_forum/admin/assets/css/media.css
- core/components/com_forum/admin/assets/js/media.js
- core/components/com_forum/admin/controllers/media.php
- core/components/com_forum/admin/controllers/threads.php
- core/components/com_forum/admin/language/en-GB/en-GB.com_forum.ini
- core/components/com_forum/admin/views/media/tmpl/display.php
- core/components/com_forum/admin/views/media/tmpl/index.html
- core/components/com_forum/admin/views/threads/tmpl/edit.php
Refs: https://help.hubzero.org/support/ticket/11852
> [feat] Adding ability to remove files from posts

- core/components/com_courses/api/controllers/assetv1_0.php
Fixes: https://mygeohub.org/support/ticket/1447
> [fix] Handle cases where INI values aren't Mb

- core/components/com_tags/admin/controllers/tagged.php
> Update default tagged item sorting field

- core/components/com_projects/site/controllers/projects.php
Refs: https://purr.purdue.edu/support/ticket/2049
> [fix] Redirect back to the right spot

- core/components/com_tools/site/assets/css/status.css
- core/components/com_tools/site/controllers/status.php
- core/components/com_tools/site/router.php
- core/components/com_tools/site/views/status/tmpl/index.html
- core/components/com_tools/site/views/status/tmpl/status.php
- core/components/com_tools/site/views/status/tmpl/status.xml
- core/components/com_tools/tables/status.php
[feature]  Addition of a tools status page. Display general current tool usage.
> Tools status page

- core/components/com_publications/tables/publication.php
Rewrite the table joins to properly displayed tagged publications.
> [fix] Properly join tables to allow showing tags properly

- core/components/com_resources/admin/controllers/items.php
Admin resource save, make sure to update the 'access' value before saving
> [fix] Save access value

- core/assets/less/tags.less
- core/assets/less/variables.less
- core/components/com_courses/site/views/courses/tmpl/_tags.php
- core/components/com_tags/site/controllers/tags.php
- core/components/com_tags/site/views/tags/tmpl/_cloud.php
- core/components/com_tags/site/views/tags/tmpl/browse.php
- core/components/com_wishlist/site/views/wishlists/tmpl/_tags.php
- core/plugins/resources/about/about.php
- core/plugins/resources/about/views/index/tmpl/default.php
This is the full core tags feature developed mostly for nanoHub.
> core tags feature

- core/components/com_projects/models/project.php
fixes: https://purr.purdue.edu/support/ticket/2109
> [com_projects] Ensure project params are parsed

- core/components/com_members/models/import/record.php
fixes: https://vhub.org/support/ticket/1996
> [com_members] Assign email address variable

- core/plugins/members/profile/assets/js/profile.js
fixes: https://vhub.org/support/ticket/2057
> Update jQuery load function call

- core/components/com_members/admin/controllers/quotas.php
- core/components/com_members/admin/views/quotas/tmpl/display.php
Member Quotas can now be synced to system
> Member Quotas can now be synced to system

- core/components/com_members/admin/controllers/members.php
fixes: https://qubeshub.org/support/ticket/1640
> [com_members] Update name persistence code

- core/plugins/resources/related/related.php
- core/plugins/resources/related/views/browse/tmpl/mini.php
fixes: https://nanohub.org/support/ticket/361954
> [plg_resources_related] Fix group wiki link logic

- core/components/com_members/api/controllers/profilesv1_0.php
- core/components/com_members/site/assets/js/register.js
fixes: https://datacenterhub.org/support/ticket/514
> Update username to password comparison code

- core/components/com_publications/site/assets/css/curation.css
fixes: https://purr.purdue.edu/support/ticket/2115
> [com_publications] Update curation fancybox styles

- core/components/com_members/models/member.php
fixes: https://nanohub.org/support/ticket/345893
> Focus member search result fields

- core/components/com_publications/site/views/view/tmpl/default.php
> [fix] Fixes incorrect argument on stripslashes

- core/bootstrap/version.php
- core/components/com_tags/models/objct.php
https://nanohub.org/support/ticket/363916
> don't copy tags over if item already has a tag

- core/components/com_tags/admin/controllers/tagged.php
- core/components/com_tags/admin/views/tagged/tmpl/display.php
fixes: https://nanohub.org/support/ticket/365565
> Refactor tagged list pagination logic

- core/components/com_wiki/site/controllers/pages.php
- core/components/com_wiki/site/language/en-GB/en-GB.com_wiki.ini
- core/components/com_wiki/site/views/pages/tmpl/submenu.php
https://nanohub.org/support/ticket/365360
> Wiki help no edit

- core/components/com_resources/site/assets/js/hubpresenter.js
> Remove JQuery nonconflict mode breaking the $ function. 

- core/components/com_tools/models/tool.php
Fixes https://nanohub.org/support/ticket/364504
> Check if submitted users and groups exist

- core/components/com_groups/admin/assets/js/groups.js
- core/components/com_groups/admin/views/pages/tmpl/scan.php
fixes: https://mygeohub.org/support/ticket/1565
> Fix group page content scanning form

- core/components/com_support/site/views/tickets/tmpl/ticket.php
fixes: https://purr.purdue.edu/support/ticket/2128
> Remove note stating that commenting reopens ticket

- core/plugins/projects/publications/views/browse/tmpl/_row.php
New pubs link to reflect publication id and version id.
> update new pubs link

- core/components/com_tags/site/views/tags/tmpl/view.php
Keep parameters both for sorting and pagination to be able to both sort and paginate :)
Fixes https://nanohub.org/support/ticket/366022
> Let sorting and changing pagination display limit at the same time

- core/components/com_resources/admin/controllers/items.php
Fixes https://nanohub.org/support/ticket/361959
> Use proper method to retrieve correct user info

- core/plugins/projects/team/assets/js/team.js
fixes: https://cdmhub.org/support/ticket/1803
> Remove automatic addition of project members

- core/components/com_resources/site/assets/js/hubpresenter.js
The paused video on load was showing the "pause" button -- setting it to "play".
Removed some commented out code.
Fixes: https://nanohub.org/support/ticket/367831
> Set the video play/pause button to play on load

- core/components/com_projects/models/adapters/nogit.php
fixes: https://cdmhub.org/support/ticket/1941
> Allow manipulation of files starting with hyphen (`-`)

- core/components/com_publications/models/curation.php
Avoid clobbering READMEs attached by users
fixes: https://purr.purdue.edu/support/ticket/2158
> Change publication README file name

- core/plugins/projects/files/assets/js/fileupload.jquery.js
Solves https://stemedhub.org/support/ticket/710
> Accept any uploaded file format if no accepted formats specified

- core/plugins/hubzero/comments/assets/css/comments.css
- core/plugins/hubzero/comments/comments.php
- core/plugins/hubzero/comments/comments.xml
- core/plugins/hubzero/comments/language/en-GB/en-GB.plg_hubzero_comments.ini
- core/plugins/hubzero/comments/views/view/tmpl/default.php
Add a parameter to a plugin to set the default comments sorting (Newest first vs Oldest first)
> Add comments sorting functionality

- core/components/com_projects/site/controllers/setup.php
- core/components/com_projects/site/views/setup/tmpl/describe.php
https://purr.purdue.edu/support/ticket/2175
> Save access selection when creating a project

- core/plugins/xmessage/handler/handler.php
Fixes issue reported by cdmhub and likely an old one from purr regarding corrupted group email. Issue was in how Swiftmailer encoded multi-line subjects and how Outlook desktop client failed to decode them (other mail clients had no problem with it). This patch fixes the issue at a low level making sure that all outgoing message subjects are in a form less likely to result in Swiftmailer encoding them in a way that Outlook does not like. At a higher level the subject probably shouldn't have been set the way it was to begin with (with \r\n line breaks) but I did not track that down or fix it.
> ensure valid subject line in mail messages

- core/components/com_publications/site/views/curation/tmpl/display.php
… for those pubs that have no review history
> Stop displaying current user/today date as the last reviewed info 

- core/components/com_resources/site/controllers/resources.php
Fixes [HABRI Central #880](https://habricentral.org/support/ticket/880)
> Cherry-pick/alias fields so ORM doesn't overwrite `id`

- core/components/com_resources/site/assets/css/video.css
Fixes https://cdmhub.org/support/ticket/1983
> Prevent the preview blocking the controls

- core/components/com_resources/site/controllers/resources.php
Include protected resources in results
fixes: https://stemedhub.org/support/ticket/717
> Update resources publications query

- core/plugins/resources/usage/language/en-GB/en-GB.plg_resources_usage.ini
- core/plugins/resources/usage/usage.php
fixes: https://nanohub.org/support/ticket/363102
> Retrieve previous months stats if users null

- core/templates/kimera/html/com_resources/view/workshops.php
Prevent SQL injection vulnerability by doing input validation on sortby against an array of possible values.
> Fix SQL injection on sortby

- core/components/com_courses/site/views/course/tmpl/_instructor.php
This is the Bio part of the course page, e.g. https://nanohub.org/courses/NPM
> Parse content to add extra security attributes to external links

- core/components/com_events/site/views/browse/tmpl/item.php
Don't hide events that are still going.
Fixes https://nanohub.org/support/ticket/376535
> Properly display events in time

- core/components/com_resources/site/assets/js/resources.js
Let the user go to the page that does all the checks
> Remove the JS call to open video without checking permissions.

- core/components/com_events/admin/controllers/pages.php
https://geodynamics.hubzero.org/support/ticket/8?show=24&search=&limit=50&start=0
> Fix events ordering in the admin

- core/components/com_tools/api/controllers/sessionsv1_0.php
usernames support more than just letters and numbers, this PR fixed the regular expression to match xusers
> Get results for users with _. characters in their usernames

- core/libraries/Hubzero/Content/Migration/Macros/AddTemplateEntry.php
Fixes: https://github.com/hubzero/hubzero-cms/issues/1489
> Fix: Update correct table when adding a template
