- core/components/com_publications/models/curation.php
- core/plugins/user/ldap/ldap.php
This fixes the bug where clicking `review & submit to be published` will take the user to a block other than the review block.
> [HUBZERO][#10328][COM_PUBLICATIONS] Fixed getting the block ID in the curation model.

- core/plugins/projects/files/files.php
- core/plugins/projects/files/files.xml
- core/plugins/projects/files/views/browse/tmpl/display.php
The changes are regarding the project quota issue. When the user browses the list of the files in the particular project, he is shown the total disk space occupied = “disk space occupied by the current version of the files” + “disk space occupied by the previous versions of the file”. What we consider is that the old versions shouldn't count against a project's quota. So we make changes to the logic of disk usage calculation in Projects-Files plugin so that the total disk space only shows the space occupied by the current version of the files. 
The code changes involves three files as showing up below. 
\core\plugins\projects\files\views\browse\tmpl\display.php 
\core\plugins\projects\files\files.php
\core\plugins\projects\files\files.xml
Fore more details, please refer to …
> [PLG_PROJECTS_FILES][TICKET #1255]Fix the project quota issue

- core/components/com_members/site/controllers/orcid.php
- core/components/com_members/site/views/orcid/tmpl/display.php
There are two changes in this request. One is the new ORCID creation process. Another is the ORCID API upgrade.
The existing “Create-and-claim” workflow causes millions of ORCID ID created but never claimed and used . So ORCID carries out the create-on-demand workflow to ask people register ORCID by themselves and get the ORCID Id instantly.
The change about ORCID API is that ORCID has upgraded the API from version 1.2 to version
2.0. The API version 2.0 has been live on production since February 14 2017. 
For details please refer to ticket #1314 through link below.
https://purr.purdue.edu/support/ticket/1314?show=107&search=&limit=20&start=0
> [PURR][#1314] Using new ORCID creation workflow and upgrade API to version 2.0

- core/components/com_members/site/controllers/orcid.php
- core/components/com_members/site/views/orcid/tmpl/display.php
The pop-up form doesn't show any ORCID searching result after clicking on the "Find your ORCID" on user's profile page. The reason is that the ORCID search response has changed. At the moment there's no name associated with the ORCID ID return which cause the search fail and no results return.
The ORCID API 2.0 search functionality introduction can be accessed through link below: 
https://members.orcid.org/api/tutorial/search-orcid-registry
According to the introduction, client has to get the record access token, and then perform the search. So the fix to the issue contains the items below.
1. Add process to get the ORCID record access token, then perform the search by name and email address.
2. Get the name associated with each ORCID ID in the search results in step 1. It has to search …
> [PURR][#1461]Fix the ORCID search issue

- core/components/com_projects/api/controllers/filesv1_0.php
- core/components/com_projects/api/router.php
- core/components/com_tools/config/fields/resourcetype.php
Hi, 
I've created a pull request to add a chunked upload API method that uses the same logic as the HTML5 chunked upload Javascript library (https://github.com/flowjs/flow.js) that we use in the iData Storage connector web upload page on MyGeoHub. We need this API to enable large file transfers from HydroShare into hub projects on MyGeoHub. 
Please review and let me know if any changes need to be made. 
Thanks,
Rajesh
> Chunked upload api

- core/plugins/authentication/shibboleth/fields/get-rs-entities.php
- core/plugins/authentication/shibboleth/fields/institutions.php
- core/plugins/authentication/shibboleth/shibboleth.php
1. Filtering the InCommon metadata to look for research & scholarship entities took too much memory and the PHP limits had to be raised. I split the method off into a different file that gets 'exec'-ed instead, and meanwhile changed the caching strategy so the page loads quickly more often.
2. Enabling the plugin without adding any institutions on the back-end caused an error. Changed this to just show an empty list of providers instead.
> Fix shibboleth plugin issues brought up during QubesHub deployment

- core/plugins/projects/files/assets/js/fileupload.jquery.js
A confirm dialog box will be opened when a file with a blank type is
queued for upload in order to notify the user that the upload may not
succeed
refs: https://purr.purdue.edu/support/ticket/1641
> [feat] Add notification to project files upload

- core/components/com_publications/models/doi.php
The change is to make the code be able to parse the response from the DataCite DOI minting request. The request is built with DataCite API, which is going to replace the EZID API, which is used on Hubzero platform now, by the end of year. The test result shows that the change doesn't have any side effect to the EZID API which is being used on Hubzero platform now.
> [PURR][#1619]Support parsing the response to the DataCite DOI minting request

- core/components/com_projects/helpers/urlHelper.php
- core/plugins/projects/files/files.php
Side menu will now display links to other file system connections
Links to file system connections will lead to a project's ~/public
directory if the user is not a member of the project
Refs: https://mygeohub.org/support/tickets/1191
> [feat] Display file connectors in project menu

- core/libraries/phpass/PasswordHash.php
PHP 7 throws a deprecation error when using classname for the constructor. Simple rename to __construct.
> [amoebahub] use __construct instead of class name for constructor [PHP7]

- index.php
Allow seperation of PATH_CORE from PATH_ROOT so same
code base can serve multiple document roots (amoebahub).
> [amoebahub] dynamically determine document root from superglobal

- core/libraries/joomla/filesystem/path.php
PATH_CORE is outside the document root in Amoebahub. This fixes one instance where the assumption is otherwise.
> [amoebahub] JPath::check() also check in PATH_CORE which may not be under JPATH_ROOT

- core/components/com_tools/api/controllers/sessionsv1_0.php
We're doing some web components to support notebook (and other web) interfaces to Rappture tools. These can be generated from the already-existing tool.xml definitions, so I'd like to expose them for that purpose.
I added an optional xpath as a convenience so that components can render only relevant sections of controls.
> [COM_TOOLS][API] add endpoint that returns tool.xml for alternate UIs

- core/components/com_members/helpers/utility.php
Email validator on registration check is balking at long top level domains which can now be up to 63 characters long (webmaster@myhub.localdomain comes up on some test builds)
>  fix validemail registration check to allow longer label parts

- core/components/com_publications/helpers/html.php
- core/components/com_publications/models/attachments/data.php
- core/components/com_publications/models/attachments/file.php
- core/components/com_publications/models/bundle.php
- core/components/com_publications/models/curation.php
- core/components/com_publications/site/assets/css/filelist.css
- core/components/com_publications/site/assets/css/publications.css
- core/components/com_publications/site/assets/js/publications.js
- core/components/com_publications/site/language/en-GB/en-GB.com_publications.ini
- core/components/com_publications/site/views/about/tmpl/_bundle_directory.php
- core/components/com_publications/site/views/about/tmpl/_bundle_file.php
- core/components/com_publications/site/views/about/tmpl/_bundle_metadata.php
- core/components/com_publications/site/views/about/tmpl/default.php
- core/components/com_publications/site/views/view/tmpl/_primary.php
- core/templates/kimera/html/com_publications/publications.css
This adds a dropdown menu to the main bundle download button. The menu
cotnains a link to display the contents of the bundle, which laucnhes
a modal window and lists the files and directories included in the
bundle and the checksum hash.
> [feat] Moving bundle contents to modal & styling it

- core/components/com_support/site/controllers/tickets.php
Previous code would list blocked users as a potential assignee of a
ticket
> [fix] Don't list blocked users as assignees 

- core/components/com_support/site/controllers/tickets.php
Previous code would list blocked users as a potential assignee of a
ticket when a group was already selected
>  [fix] Don't list blocked users as assignees

- core/plugins/authentication/shibboleth/shibboleth.php
Per hubzero ticket. shibd needs to pass a bunch of state to itself through this parameter, but it should always begin with https://hubhost/Shibboleth.sso/ so I assert that. Failures go back to the login page.
> shibboleth - ensure return parameter is local

- core/components/com_groups/models/page.php
- core/components/com_groups/site/views/pages/tmpl/list.php
The code would pull all versions for a page when only the latest was
needed. This could cause serious memory issues for a gorup that has
many pages, many versions of a page, or both.
Fixes: https://nanohub.org/support/ticket/329866
> [fix] Only pull the latest version instead of all

- core/components/com_cart/migrations/Migration20180718194712ComCart.php
Queries that specify a scope_id have caused a high database load; this index fixes the issue.
> Create an index on jos_cart_meta scope_id

- core/components/com_blog/site/controllers/entries.php
- core/plugins/blog/opengraph/language/en-GB/en-GB.plg_blog_opengraph.ini
- core/plugins/blog/opengraph/language/en-GB/en-GB.plg_blog_opengraph.sys.ini
- core/plugins/blog/opengraph/migrations/Migration20180721000000PlgBlogOpengraph.php
- core/plugins/blog/opengraph/opengraph.php
- core/plugins/blog/opengraph/opengraph.xml
- core/plugins/blog/twitter/language/en-GB/en-GB.plg_blog_twitter.ini
- core/plugins/blog/twitter/language/en-GB/en-GB.plg_blog_twitter.sys.ini
- core/plugins/blog/twitter/migrations/Migration20180722000000PlgBlogTwitter.php
- core/plugins/blog/twitter/twitter.php
- core/plugins/blog/twitter/twitter.xml
- core/plugins/groups/blog/blog.php
- core/plugins/members/blog/blog.php
This adds an `onBlogView` event for when viewing an article and two
plugins that respond to said event. Each plugin pushes meta tags to the
document to aid in search (open graph) and Twitter.
Refs: https://cdmhub.org/support/ticket/1578
> [feat] Event call and plugins for OG & Twitter

- core/components/com_groups/helpers/pages.php
- core/components/com_groups/models/page.php
Group pages can now have the same alias, as long as they have a different
parent element.
refs: https://qubeshub.org/support/ticket/1224
> [fix] Allow group pages to share the same alias

- core/components/com_publications/site/controllers/publications.php
This covers a case where a user might fork their own publication and,
thus, they are already an author. We don't want to add them again.
Fixes: https://qubeshub.org/support/ticket/1211
> [fix] Ensure user isn't author before adding them

- core/components/com_groups/site/controllers/membership.php
- core/components/com_groups/site/views/membership/tmpl/invite.php
This allows for passing a list of usernames or email addresses to
pre-populate the "to" field for the group invitation form. Each "to"
passed is validated before being passed to the form.
> [feat] Allow passing array of values to form

- core/components/com_members/site/assets/js/register.js
Passing values as a querystring can cause characters in the password,
such as an ampersand (&), to be misinterprutted and truncate the pass.
Fixes: https://hubicl.org/support/ticket/14
> [fix] Don't pass values as querystring

- core/components/com_wiki/models/page.php
Sometimes, when a user doesn't have permission for an action, the result
of the authorise check is `NULL`, for `false`. So, we take that into
account.
Fixes: https://nanohub.org/support/ticket/331290
> [fix] Fixing how permissions are calculated

- core/components/com_answers/helpers/permissions.php
- core/components/com_blog/admin/helpers/permissions.php
- core/components/com_citations/helpers/permissions.php
- core/components/com_collections/helpers/permissions.php
- core/components/com_courses/helpers/permissions.php
- core/components/com_cron/helpers/permissions.php
- core/components/com_developer/helpers/permissions.php
- core/components/com_feedback/helpers/permissions.php
- core/components/com_forum/helpers/permissions.php
- core/components/com_jobs/helpers/permissions.php
- core/components/com_kb/admin/helpers/permissions.php
- core/components/com_members/helpers/permissions.php
- core/components/com_newsletter/helpers/permissions.php
- core/components/com_oaipmh/helpers/permissions.php
- core/components/com_poll/helpers/permissions.php
- core/components/com_projects/admin/views/projects/tmpl/description.php
- core/components/com_projects/admin/views/projects/tmpl/display.php
- core/components/com_publications/helpers/permissions.php
- core/components/com_resources/helpers/permissions.php
- core/components/com_services/helpers/permissions.php
- core/components/com_storefront/admin/helpers/permissions.php
- core/components/com_support/helpers/permissions.php
- core/components/com_tags/helpers/permissions.php
- core/components/com_wiki/helpers/permissions.php
- core/components/com_wishlist/helpers/permissions.php
Asset type should only be appended to the permission string when a
specific asset ID is provided. Otherwise, it can lead to incorrect
calculations and give permission where it was meant to be denied.
> [fix] Fixing issue with how permissions are calc.

- core/components/com_tools/admin/controllers/hosts.php
Previous var default value was an integer but the rest of the code was
expecting an array.
Fixes: https://help.hubzero.org/support/ticket/11493
> [fix] Make default value of var to be correct type

- core/components/com_groups/site/controllers/membership.php
Fixes: https://help.hubzero.org/support/ticket/11504
> [fix] Use group title instead of alias in emails

- core/components/com_members/site/controllers/profiles.php
- core/components/com_members/site/controllers/register.php
This allows for hooking on to and responding to more specific user
events, such as when the user confirms their account.
> [feat] Adding event triggers for more plugin points

- core/components/com_publications/models/curation.php
New publication submissions were displaying an error since it was attempting to
remove symlink that wasn't created yet.
refs: https://purr.purdue.edu/support/ticket/1879
> [fix] Only attempt to remove a symlink file if it already exists

- core/components/com_publications/migrations/Migration20180627111315ComPublications.php
- core/components/com_publications/migrations/Migration20180820101435ComPublications.php
- core/components/com_publications/models/curation.php
- core/components/com_publications/models/publication.php
Absolute paths to the original publication file were not accessible via FTP.
I changed the symlinks to reference the relative path instead.
refs: https://purr.purdue.edu/support/ticket/1852
> [fix] Change publication ftp bundle symlink to reference relative paths.

- core/components/com_support/models/ticket.php
Without the additional check, the new Query instance continues through
the function, which attempts to access a property on a null return value
provided by the Query
fixes: https://help.hubzero.org/support/tickets/11502
> Add condition to Ticket::allWithQuery

- core/components/com_tools/tables/version.php
Doing `v.*, d.*` can result in two ID columns returned, resulting in
incorrect data lookups later on.
Fixes: https://nanohub.org/support/ticket/332127
> [fix] Only grab needed fields

- core/index.php
This allows setting `PATH_CORE` via an environment variable. If no env
var is found, it will fallback to previous functionality (assumes it's a
directory under `PATH_ROOT`).
This also allows for running the CMS from `/core`.
> [feat] Allow set PATH_CORE by env var and run from core

- core/components/com_groups/models/import/record.php
- core/components/com_members/models/import/record.php
Handlers are loaded statically, so errors added to them after each use
can build up, falsely reporting errors for records that may not have
generated any. So, clear the error bag after each time the handler is
used.
> [fix] Clear handlers' error bags after each use

- core/components/com_groups/site/views/media/tmpl/filelist.php
Try getting the extensionf romt he file name before resorting to content
type detection. The latter method can be especially process heavy with
larger files.
Fixes: https://mygeohub.org/support/ticket/1303
> [fix] Try getting extension from file name

- core/plugins/user/autoapprove/autoapprove.php
- core/plugins/user/autoapprove/autoapprove.xml
- core/plugins/user/autoapprove/language/en-GB/en-GB.plg_user_autoapprove.ini
- core/plugins/user/autoapprove/language/en-GB/en-GB.plg_user_autoapprove.sys.ini
- core/plugins/user/autoapprove/migrations/Migration20180831000000PlgUserAutoapprove.php
This plugin allows for auto-approving new accounts based on if their
email matches a specified regex. For exaple, any email that ends in
`.edu` could be considered trusted and autoapproved.
> [feat] Autoapprove users based on email

- core/plugins/projects/publications/publications.php
This moves the instantiation of the DOI service object from outside an
`if` statement as it's needed further on in the code.
Fixes: https://qubeshub.org/support/ticket/1270
> [fix] Make sure doiService obj is available

- core/assets/js/jquery.fancyselect.js
CSS selector text should be in quotes just in case it has things like
parentheses in it, which could truncate the selector statement. Example:
`.foo span:contains(bad (text))`
Fixes: https://qubeshub.org/support/ticket/1273
> [fix] Quote text to guard against bad characters

- core/plugins/projects/links/links.php
Currently the query returns true (citation ID) if it is attached to any publication, not just the one you are trying to attach it.
> [fix] Query for publication id when attaching the citation

- core/plugins/filesystem/dropbox/dropbox.php
- core/plugins/filesystem/googledrive/googledrive.php
- core/plugins/projects/files/connections.php
Drive adapter is not expecting subdirectories when instantiating.
Fixes: https://qubeshub.org/support/ticket/1269
> [fix] Reshaping path variable for Google Drive

- core/components/com_publications/models/curation.php
New publications submitted would have the symlink automatically created
based on DOI, however the link creation is based on pubication Id/ version Id.
> [fix] ensure publication symLink name is correct.

- core/bootstrap/Administrator/Providers/DocumentServiceProvider.php
- core/bootstrap/Site/Providers/DocumentServiceProvider.php
We can't always rely on the path being a sub-directory of PATH_ROOT.
So, we need to take a different tact to building the baseurl.
> [fix] Better way of builing document's baseurl

- core/modules/mod_incremental_registration/helper.php
My apologies for the nanoHUB snafu. This patch fixes the bug from #333646
> incremental registration: show curl more selectively, subsequent bugfix

- core/components/com_resources/admin/views/items/tmpl/edit.php
Edit resource page would throw an undefined variable error
if no badges existed for the resource.
refs: https://pharmahub.org/support/tickets/685
> [fix] Ensure resource badges variable is set

- core/components/com_templates/admin/controllers/source.php
The method is expecting an array with a key of 'source', not a string.
Fixes: https://help.hubzero.org/support/ticket/11561
> [fix] Pass entire array to method

- core/migrations/hooks/UpdateTimezoneDatabase.php
In some cases (Amazon RDS) it will not be possible to run the timezone data update hook. So catch the error and display a warning rather than abort with a messy exception error.
> Catch failure when running timezone data update hook

- core/components/com_kb/site/router.php
This fixes an issue where nested category alias (/kb/tools/padre) would
be incorrectly routed as an article. Now, it checks to see if the
second segment (padre) is a category alias first, before assuming it's
an article alias.
> [fix] Handle case of nested category

- core/components/com_resources/models/screenshot.php
- core/components/com_tools/migrations/Migration20181015161919ComTools.php
- core/components/com_tools/site/controllers/screenshots.php
This adjusts how filenames are being saved. Previously, the period
before the file extension (.png) was being stripped. This should fix
old, bad data, and prevent it from happening in the future.
Fixes: https://nanohub.org/support/ticket/333739
> [fix] Fixing issues with reordering screenshots

- core/components/com_citations/models/citation.php
We only want to get the earlist year for citations within the given
scope, not all citations.
Fixes: https://nanohub.org/support/ticket/334188
> [fix] Filter earliest year lookup by scope

- core/components/com_resources/models/entry.php
Resources was not able to be indexed since an invalid character
existed in a customfield key.
refs: https://qubeshub.org/support/tickets/1312
> [fix] Remove invalid characters from solr custom field key

- core/composer.lock
This should bring in minor bug fixes for the ORCID library and PHP 7
fixes for the framework. Also Replaces deprecated PHPExcel with
PHPSpreadsheet.
Refs: https://github.com/hubzero/orcid-php/commit/2b9a31bd3932af0e18d4b80029901c8ec84a0861
Refs: https://github.com/hubzero/framework/commit/caf117e96701900acb1857471bb79b1860949d44
Refs: https://github.com/hubzero/framework/commit/6bfc4d97560d474b409a6dfc8c57b417b045c475
Refs: https://github.com/hubzero/framework/commit/38fecad259e51fc76181eed20d87cc44b4430923
Refs: https://github.com/hubzero/framework/commit/c47f0b1e642822843f3f35356e845a2ea4084265
Refs: https://github.com/hubzero/framework/commit/f3f56ea34cecc4701fdd948eb28ebf964a8fd7b8
Refs: https://github.com/hubzero/framework/commit/b4b8fb47552da8832c3cbc2f6d0fce1b0688d94a
> [maint] Bumping framework and ORCID-PHP

- core/plugins/cron/newsletter/language/en-GB/en-GB.plg_cron_newsletter.ini
- core/plugins/cron/newsletter/newsletter.php
- core/plugins/cron/newsletter/newsletter.xml
Previous code would try to grab all unprocessed records. Normally, this
shouldn't be a problem but there may be cases where the total builds
up to an unmanageable point and records need to be processed in batches.
> [fix] Process IPs in batches

- core/plugins/projects/links/views/selector/tmpl/edit.php
Update the form's URL field name to the correct one to be saved properly
> [fix] Save the citation URL

- core/components/com_dataviewer/site/controller.php
- core/components/com_dataviewer/site/filter/csv.php
Removing output buffer functions allows CSV data to be sent to client
fixes: https://purr.purdue.edu/support/ticket/1962
> Update com_dataviewer download code

- core/modules/mod_rapid_contact/helper.php
Name value would get sanitized after being used in the message. Now
we check for its existence and sanitize before that.
> [fix] Moving sanitization line

- core/plugins/members/blog/blog.php
- core/plugins/members/blog/views/entry/tmpl/default.php
This fixes an issue where, if there were two posts with the same alias
but one was marked as deleted, the system would sometimes attempt to
load the deleted entry. Also fixes an issue with displaying deleted
entries in the 'popular entries' list.
Fixes: https://nanohub.org/support/ticket/335993
> [fix] Don't load or show deleted entries

- core/components/com_projects/helpers/html.php
Project Feed time was displaying in GMT instead of local time.
It seems there was an issue with it recieving a time string
ran through strtotime as well as an issue with the way the time was
combined.
refs: https://qubeshub.org/support/tickets/1326
> [fix] Ensure project feed time is correctly coverted

- core/components/com_publications/models/attachments/publication.php
Replace loadVersion() that looks up by `publication_id` with the `load` that looks up by `id`, since the view is providing the `id`s
> Series attachments fix

- core/components/com_projects/models/repo.php
Some path vars empty states are not equivelant. An empty string means
the top (root) path. NULL means the path var was not set.
> [fix] Allow files to be moved up a dir or to root

- core/plugins/user/middleware/middleware.php
If a user is manually set to a quota class, the old code would overwrite
values due to only looking for 'custom' or access group associated
classes. This should ensure that values only change if an associated
access group quota class has higher values.
Fixes: https://nanohub.org/support/ticket/339013
> [fix] Only overwrite values if they're greater than what's set

- core/components/com_resources/models/entry.php
The tool link was always showing as 'dev' instead of the active version
> [fix] Ensure tool info is populated to generate proper tool link

- core/components/com_groups/models/page/version.php
Permissions issues were occuring within the vendor directory for
HTMLPurifier. Set the configuration so it knows to put tmp files into
the CMS tmp directory.
refs: https://mygeohub.org/support/ticket/1332
> [fix] specify HTMLPurifier tmp file location

- core/components/com_wiki/site/controllers/pages.php
Fixes: https://help.hubzero.org/support/ticket/11659
> [fix] Ensure returned value is an integer

- core/components/com_publications/admin/views/licenses/tmpl/edit.php
- core/components/com_publications/models/orm/license.php
Can't directly call `main` like a property as it will, instead, call the
`main()` method. Use the `isMain()` method or getter.
Fixes: https://purr.purdue.edu/support/ticket/1983
> [fix] Use proper method for checking if is main license

- core/components/com_resources/models/author.php
Using `Member::one()` will return a boolean if it fails to find a record
which wil throw an error on following lines that are expecting an object
> [fix] Make sure method called returns an object

- .travis.yml
When files are removed, the sniffer has problems scanning them.  This should filter files based on whether they exist or not before sending them to phpcs.
> [fix] Updating .travis.yml

- core/components/com_groups/admin/controllers/manage.php
- core/components/com_groups/admin/language/en-GB/en-GB.com_groups.ini
- core/components/com_groups/helpers/gitlab.php
Updated get requests for groups and projects to use Gitlab's API search function and to only get groups or project for the current hub Gitlab user instead of all groups or project on Gitlab.
Fixes https://qubeshub.org/support/ticket/1349 .
>  Updated get requests for groups and projects

- core/components/com_wiki/site/views/special/tmpl/filelist.php
The special view for listing all files in a wiki would show files from
deleted pages as well despite them not being accessible.
Fixes: https://nciphub.org/support/ticket/1539
> [fix] Don't display deleted content

- core/components/com_resources/models/doi.php
DOI Service config is a stdClass, not a hubzero registry class. This
means retrieval via direct property rather than a getter.
> [fix] Fixing how property is retrieved

- core/components/com_members/admin/views/members/tmpl/edit_user.php
- core/components/com_members/site/views/register/tmpl/default.php
- core/components/com_support/admin/views/tickets/tmpl/add.php
- core/components/com_support/site/views/tickets/tmpl/new.php
- core/modules/mod_rapid_contact/tmpl/default.php
- core/modules/mod_reportproblems/tmpl/default.php
The email input type offers better semantics, will prompt mobile devices
to use a keyboard more appropriate for typing addresses (easy access to
'@'), and falls back to standard 'text' field.
> [refactor] Changing input type to 'email'

- core/components/com_wiki/site/views/pages/tmpl/submenu.php
- core/components/com_wiki/site/views/pages/tmpl/wikimenu.php
The `sub` flag used to determine if `action` or `task` was used in a
URL. But this can't be relied on as super group wikis had `sub` set to
`false` but need to use `action`, not `task`, in URLs.
Fixes: https://cdmhub.org/support/ticket/1800
> [fix] Fixing how new page link is built

- core/components/com_groups/helpers/pages.php
Fixes: https://qubeshub.org/support/ticket/1360
> [fix] Set the `option` var used in asset helpers

- core/plugins/content/formathtml/macros/video.php
- core/plugins/wiki/parserdefault/macros/video.php
Help text used http links for examples. This caused confusion with
allowed URLs (mixed source content is blocked by browsers under https).
Refs: https://qubeshub.org/support/ticket/1285
> [fix] Updating documentaiton to use https

- core/components/com_courses/site/controllers/form.php
The params were set to expect a string,
therefore array values couldn't be accessed.
fixes: https://nanohub.org/support/ticket/342375
> [fix] Ensure course quiz deployment gets array.

- core/components/com_resources/models/doi.php
This will handle a case where the returned registered DOI includes the
shoulder (e.g., shoulder/doi). Both parts are stored separately, so the
string needs to be broken into its parts.
> [fix] Adding guard against shoulder inc with DOI

- core/components/com_users/site/views/login/view.html.php
A few lines above, `Request::getString()` is forcing a return value of
a string, regardless of `null` being passed as a default value. So
the `is_null()` check fails every time.
Fixes: https://help.hubzero.org/support/ticket/11730
> [fix] Check if var is an empty string

- core/components/com_menus/admin/controllers/items.php
The `cancelTask()` method called after saving looks for a model it might
need to checkin. The model lookup is the same as in `saveTask()` before
the edited data is applied to the model. This means the data is cached
and the lookup in the cancel task is returning _old_ data that
overwrites the just-saved changes. So, we purge the cache before
cancelling.
> [fix] Fixing issue with 'save & close'

- core/components/com_installer/admin/views/migrations/tmpl/display.php
muse expects only the filename and then searchs its own list of
directories for that file.
> [fix] Use only the filename not path

- core/components/com_projects/models/orm/project.php
- core/components/com_projects/models/project.php
This fixes an issue with a namespace being declared as already in use.
Discovered when trying to change a project's associated image.
> [fix] Declaring namespaces

- core/components/com_tags/models/tag.php
As we may need to recalculate the number of tagged items or
substitutions multiple times in a batch process, we don't want to keep
returning the same cached result.
Fixes: https://habricentral.org/support/ticket/839
> [fix] Don't cache query results

- core/plugins/usage/tools/tools.php
Previously, it would default to a date range for the most current month
but, if there was no data for that value, a blank page would result
(and no item in the select list). This change starts with the current
date range and walks backwards until it finds a value with associated
data.
> [fix] Find first date range with data

- core/components/com_dataviewer/site/html/spreadsheet.js
fixes: https://purr.purdue.edu/support/ticket/1997
When `bServerSide` is true, column filters only include values present in the visible rows as opposed to showing the values for all rows.
It seems like a request associated with `bServerSide` being true fails.
> [fix] Update datatable config to fix search inputs

- core/plugins/resources/reviews/helper.php
- core/plugins/resources/reviews/models/review.php
- core/plugins/support/resources/resources.php
The Review model was missing a static method for calculating the
average review rating for a resource.
Fixes: https://nanohub.org/support/ticket/344660
> [fix] Adding missing method

- core/components/com_wiki/models/link.php
Sometimes links have no scope ID. We only want to set the value on the
model when a value is actually present.
Fixes: https://help.hubzero.org/support/ticket/11755
Fixes: https://help.hubzero.org/support/ticket/11758
> [fix] Make sure scope_id isn't null

- core/components/com_resources/admin/controllers/imports.php
The import model referenced when attempting to delete an import
was pointing to the wrong import namespace.
fixes: https://habricentral.org/support/ticket/848
> [fix] Ensure removing an import points to the correct Import model

- core/components/com_newsletter/admin/views/newsletters/tmpl/send.php
The JS was looking for a specific ID and, not finding it, couldn't
submit the form.
Fixes: https://qubeshub.org/support/ticket/1382
> [fix] Adding missing ID attribute on form

- core/components/com_installer/admin/controllers/packages.php
- core/components/com_installer/admin/controllers/repositories.php
- core/components/com_installer/admin/controllers/warnings.php
- core/components/com_installer/admin/helpers/installer.php
- core/components/com_installer/admin/language/en-GB/en-GB.com_installer.ini
- core/components/com_installer/admin/views/warnings/tmpl/composer.php
- core/components/com_installer/config/composer.json.dist
Check for the required `composer.json` file first and, if not found, try
to provide a sample with the required `hubzero/extension-installer`.
> [feat] Provide sample composer.json content

- core/components/com_whatsnew/migrations/Migration20170831000000ComWhatsnew.php
- core/components/com_whatsnew/migrations/Migration20190306000000ComWhatsnew.php
Also, don't specify the checked_out_time column when inserting menu
entries. The default value has changed over time and it's better to let
the database handle it than specifying it in SQL.
> [fix] com_whatsnew shouldn't have admin menu item

- core/components/com_wiki/admin/controllers/comments.php
- core/components/com_wiki/admin/views/comments/tmpl/display.php
- core/components/com_wiki/admin/views/comments/tmpl/edit.php
When editing a comment, it would sometimes drop page ID info and not
properly redirect back to the correct comments list. Also minor display fix.
> [fix] Remember what page the comments list was for

- core/components/com_citations/site/controllers/citations.php
Previous regex would validate strings such as "2016-07-22 00:00:00'A"
which would the Date class would then throw an error as not being able
to parse.
> [fix] Fixing datetime regex to be stricter

- core/components/com_dataviewer/site/html/spreadsheet.js
Server side rendering was not working, and it was required for datasets
exceeding the threshold for tables that are able to be fully loaded.
This reverts commit 5a7a5ae55ea621cc9b51e57e3155b5e57528c1c1.
fixes: https://purr.purdue.edu/support/ticket/2002
> [fix] revert commit that was preventing Dataviewer from working properly

- core/plugins/publications/jsonld/jsonld.php
[JSON+LD]Fixes to the issues of JSON+LD metadata elements
1. Extra forward slash exists in the dataset URL and author URL.
2. Escape character (\) exists in the strings of a few metadata elements, such as @context, dataset url, identifier, @id, sdLicense, and author url.
3. Add version number and publisher to JSON+LD.
> [PURR][#2007]Fixes to the issues of JSON+LD metadata elements

- core/components/com_users/site/controllers/user.php
- core/components/com_users/site/views/login/view.html.php
Fixes an issue with redirecting to the correct root path when running
a hub in a sub directory (e.g., https://localhost/hubzero/). Admittedly,
unusual, but gets things working and doesn't harm normal setups.
> [fix] Redirect to correct root path

- core/components/com_members/admin/controllers/members.php
- core/components/com_members/admin/views/members/tmpl/edit_user.php
Saving an unconfirmed account would reset the activation code every
time. We only want to reset it when going from confirmed to unconfirmed.
Also fixing incorrect table cell type.
Fixes: https://help.hubzero.org/support/ticket/11781
> [fix] Fix accidental reset of confirmation code

- core/components/com_collections/models/item.php
When collected wiki pages are displayed, they are passed through a
content prepare event. This ends up setting the wiki page's scope to
'collection', which is incorrect and throws an error.
> [fix] Fixing bug causing collected wiki to error

- core/plugins/captcha/image/language/en-GB/en-GB.plg_captcha_image.ini
- core/plugins/captcha/image/views/display/tmpl/default.php
HTML comments were causing a link scanner to act oddly. Removing them
does no harm and hopefully gets the scanner to quiet down. Also, moving
some text to language file.
Fixes: https://help.hubzero.org/support/ticket/11789
> [fix] Removing HTML comments

- core/components/com_resources/site/controllers/resources.php
We have to manually specify access values here as Resources uses a
different set thatn the standard values used elsewhere.
Fixes: https://nanohub.org/support/ticket/346165
> [fix] Add correct access values to query

- core/components/com_projects/site/assets/css/edit.css
- core/components/com_projects/site/assets/js/setup.js
- core/components/com_projects/site/controllers/setup.php
- core/components/com_projects/site/views/setup/tmpl/_edit_grant_info.php
- core/components/com_projects/site/views/setup/tmpl/describe.php
- core/components/com_projects/site/views/setup/tmpl/finalize.php
- core/templates/kimera/html/com_projects/edit.css
Only notify the sponsored projects reviewers when that info is set on a
project. This reduces noise for projects they may actually be concerned
with.
Refs: https://purr.purdue.edu/support/ticket/2011
> [fix] Only notify reviewers when grant info is set

- core/components/com_events/models/event.php
The eventdate.php file was removed since it was no longer needed,
but there was still a require_once attempting to load the file.
> [fix] Remove require_once to file that was removed.

- core/plugins/groups/calendar/calendar.php
Date was having issues statically calling Date::toSql() since
the Facade is what permitted this static call.
fixes: https://help.hubzero.org/support/ticket/11799
> [fix] remove declaring Date namespace to allow Facade to work.

- core/plugins/cron/resources/resources.php
Another plugin had a similar method name, causing the event to get
triggered when it shouldn't.
Fixes: https://communityhub.purdue.edu/support/ticket/285
> [fix] Renaming method to avoid conflicts

- core/plugins/groups/forum/views/categories/tmpl/edit.php
Locking a forum category was supposed to be a checkbox,
but it was showing as a text type.
fixes: https://qubeshub.org/support/ticket/1402
> [fix] Ensure proper input type is being used.

- core/components/com_wiki/models/link.php
When not setting scope_id, it tries to create a new record with a NULL
value. It should be entering an integer.
Fixes: https://help.hubzero.org/support/ticket/11741
> [fix] Always insert scope_id as integer

- core/components/com_wiki/site/views/pages/tmpl/submenu.php
This ensures the namespace is correctly retrieved and is lowercase.
Refs: https://help.hubzero.org/support/ticket/11642
> [fix] Get namespace the proper way

- core/components/com_citations/admin/views/citations/tmpl/edit.php
validate.js was flagging the form as being invalid because these
text areas had no text even though they weren't traditionally
required.
fixes: https://purr.purdue.edu/support/ticket/2017
> [fix] Remove 'required' class from fields that aren't required.

- core/components/com_courses/site/assets/js/plugins.js
- core/components/com_groups/site/assets/js/groups.js
- core/components/com_publications/site/assets/js/video.js
- core/components/com_resources/site/assets/js/hubpresenter.js
- core/components/com_resources/site/assets/js/video.js
Refactoring scripts to not use a deprecated method.
Fixes: https://help.hubzero.org/support/ticket/11806
> [fix] jQuery's `live()` method is deprecated

- core/components/com_support/migrations/Migration20190411000000ComSupport.php
This column should have had its default updated to `NULL` in a previous
migration but was missed.
> [fix] Catching missed datetime column

- core/assets/css/layout.css
- core/assets/css/notifications.css
- core/assets/less/layout.less
- core/components/com_courses/site/assets/css/form.css
- core/components/com_resources/site/assets/css/create.css
- core/components/com_tools/site/assets/css/tools.css
- core/plugins/courses/outline/assets/css/build.css
- core/plugins/courses/progress/assets/css/instructor.css
- core/plugins/members/profile/assets/css/profile.css
- core/templates/system/css/main.css
In some cases, the image was a fallback for old browsers that didn't
undertsand the CSS. Those browsers are now old enough we don't support
them and the fallback isn't needed.
> [maint] Replacing image with pure CSS

- core/components/com_courses/site/views/form/tmpl/layout.php
Editing a course quiz or viewing the preview as an instructor
would only show the choice marked as correct instead of all
choices.
As a result, if the quiz was then saved it was cause it to
save in this one option state.
fixes: https://smarteragriculture.org/support/ticket/258
> [fix] Ensure course questions can be properly edited.

- core/components/com_resources/admin/views/items/tmpl/edit.php
When creating a new resource on the admin side, a 'type' hasn't been
chosen yet. Custom fields are associated with types, so the code that
gets the list of fields returns `false`.
Fixes: https://nanohub.org/support/ticket/347362
> [fix] Ensure var is set before using

- core/plugins/resources/related/related.php
Previous incarnation wuld show a link for every version of a wiki page
that the resource was linked to, but not link to the actual version.
Instead, just look for associations to the most current wiki version.
Fixes: https://nanohub.org/support/ticket/347099
> [fix] Only link to current version of wiki page

- core/bootstrap/Site/routes.php
- core/components/com_projects/api/controllers/projectsv2_0.php
This helps guard against cases where the site routes might be called
from a client type that doesn't have all services registered. Use case
might be the API calling `Route::urlForClient('site', $url)`.
Refs: https://mygeohub.org/support/ticket/1393
> [fix] Check for registered objects before use

- core/components/com_modules/models/module.php
- core/components/com_plugins/models/plugin.php
- core/components/com_templates/admin/controllers/styles.php
Previously only supported by components, this adds support for a /config
directory for all other extension types. This allows for more consistent
structure across extension types.
> [feat] Look for `config` directory

- core/components/com_tags/site/controllers/tags.php
Previously, a nonexistent tag would throw up the error page. While
technically correct, it's a bad user experience.
Refs: https://help.hubzero.org/support/ticket/11616
> [fix] Little nicer user experience for bad tags

- core/components/com_search/models/basic/result/set.php
This gets the plugin lsit from the database. In some rare/odd cases, the
actual plugin files may be missing and a 500 will get thrown. So, skip
plugins that don't have files.
> [fix] Skip plugins that don't have files

- core/components/com_content/site/router.php
IDs in URL slugs are no longer needed as site routing was modified
awhile ago to support `/{category alias}/{article alias}`.
> [fix] Remove IDs from URL paths

- core/components/com_projects/helpers/nogithelper.php
- core/components/com_projects/models/adapters/nogit.php
Lightweight containers don't contain sophisticated versions of these
utilities for us to use.
> [refactor] Use flysystem local adapter

- core/plugins/groups/resources/views/results/tmpl/default.php
Adding the current limit value to the querystring preserves the limit
when filters change. Otherwise, it can revert back to the default.
Fixes: https://nanohub.org/support/ticket/348299
> [fix] Add limit to filter querystring

- core/components/com_publications/models/doi.php
The value of element "resourceType" need to be changed to "Dataset series" in DOI's metadata record that associates with a series publication. The phrase "Dataset series" is defined in CASRAI vocabulary to describe the datasets collection and datasets aggregation, which confirms to the nature of the series on PURR where series serves as a collection of datasets.
> Set the value of element "resourceType" to "Dataset series" in DOI's metadata record

- core/components/com_tools/site/controllers/pipeline.php
Previous code assumed, when there's a group ID, `getInstance` always
returns a group object. Despite having an ID, if the group itself
can't be found `getInstance` will return `false`.
Fixes: https://nanohub.org/support/ticket/349733
> [fix] Handle cases where group isn't found

- core/components/com_resources/models/author.php
Records could be processed fast enough that `time()` won't change and
result in duplicate authorids.
Fixes: https://habricentral.org/support/ticket/849
> [fix] Change how authorids are generated

- core/plugins/projects/files/assets/js/files.js
The various cotnent containers could have `position: relative` on them
which can alter how `position: absolute` co-ordinates display. So, we
move the preview box to be a child of `body` and set coordinates based
on that. This keeps the popup the same across varying templates.
Fixes: https://purr.purdue.edu/support/ticket/2024
> [fix] Set positioning against body element

- core/components/com_groups/site/assets/js/groups.js
- core/components/com_members/site/assets/js/incremental.js
- core/plugins/members/profile/assets/js/profile.js
jQuery "load" used to be used in two different ways:
an Event listener shortcut (this was has been removed)
or a simple way to fetch data from a URL.
This way is still valid.
fixes: https://nanohub.org/support/ticket/350066
> [fix] restore jQuery load where used for ajax requests.

- core/components/com_members/models/member.php
Members wasn't indexing users with an "activation" value set
to greater than 1, which would often be the case for users
who created accounts via third party authenticator.
fixes: https://nanohub.org/support/ticket/349930
> [fix] Ensure member search includes all activated members

- core/components/com_publications/models/blocks/license.php
- core/plugins/projects/publications/views/draft/tmpl/license.php
Custom licenses weren't properly showing the individual
values provided when editing, and it also did not
correctly show as being a completed block in the eyes
of curation, therefore prohibited submission.
fixes: https://nanohub.org/support/ticket/350074
> [fix] Ensure custom licenses are shown as completed

- core/components/com_groups/site/views/media/tmpl/filelist.php
This includes th base modal styles just in case the component tmpl
hasn't defined them.
Fixes: https://nanohub.org/support/ticket/350154
> [fix] Include base modal styles

- core/modules/mod_members/assets/css/mod_members.css
Sometimes the list of unique domains gets rather long. So, set a max
height on the module and allow the overflow to scroll. A better way of
grouping small domain counts is needed...
> [fix] Set a max height on the module

- core/components/com_resources/site/assets/css/create.css
- core/components/com_resources/site/assets/js/tags.js
Checking a tags category with children wasn't
properly displaying its children because of
changed behavior of jQuery .attr('checked')
fixes: https://habricentral.org/support/ticket/859
> [fix] Nested resource tags weren't appearing

- core/plugins/authentication/certificate/certificate.php
- core/plugins/authentication/cilogon/cilogon.php
- core/plugins/authentication/facebook/facebook.php
- core/plugins/authentication/google/google.php
- core/plugins/authentication/linkedin/linkedin.php
- core/plugins/authentication/orcid/orcid.php
- core/plugins/authentication/pucas/pucas.php
- core/plugins/authentication/scistarter/scistarter.php
- core/plugins/authentication/shibboleth/shibboleth.php
- core/plugins/authentication/twitter/twitter.php
In some rare cases the `Hubzero\Auth\Link::find_or_create()` method
returns a boolean `false` instead of an object.
> [fix] Handle rare case method returns `false`

- core/components/com_resources/site/controllers/resources.php
- core/components/com_resources/site/views/view/tmpl/tools.php
- core/plugins/resources/about/views/index/tmpl/default.php
If a DOI isn't found for a resource/tool, this would fallback to
buling one with a shoulder of "10254". That shoulder doesn't seem to be
valid and currently can't find any information on where it came from.
Refs: https://nanohub.org/support/ticket/350118
> [fix] Removing ref to hard-coded non-existent shoulder

- core/components/com_resources/admin/views/items/tmpl/edit.php
The `fields()` method does some extra work on parsing vlaues that
inadvertently causes said values to not be in the needed state when
rendering the input elements. This particularly affects elements with
multiple sub-options such as lat/long and dates (y/m/d).
Fixes: https://habricentral.org/support/ticket/860
> [fix] Reverting change

- core/plugins/members/collections/collections.php
Not sure why this check is in place. Traced code back to 2015 and it's
still there. Fixing immediate issue for now but this needs
re-evaluating.
Fixes: https://hubicl.org/support/ticket/124
> [fix] Adding registered' access to list

- core/plugins/search/members/members.php
This is another 
> count(): Parameter must be an array or an object that implements Countable'
error fix.  There's probably a cleaner way to write it, but this is the safest thing that worked for me.
> PHP 7 compatibility

- core/components/com_resources/site/views/steps/tmpl/tags.php
- core/components/com_search/models/basic/terms.php
- core/components/com_tags/admin/controllers/relationships.php
- core/plugins/search/publications/publications.php
- core/plugins/search/resources/resources.php
As of PHP 7.2, [create_function() is deprecated](https://www.php.net/manual/en/function.create-function.php).  I've replaced all instances I could find and test with anonymous functions.  This should be compatible with >= 5.3.0 (see link).  I didn't see any guidance on formatting anonymous functions so I went with the style I've seen in Javascript.
I noticed that geshi also has an instance of create_function().  There is a newer version out, 1.0.9.0, but it hasn't gotten rid of create_function().  So you know.  It's an external dependency so I figured I shouldn't touch it.
> replace create_function() with new anonymous function syntax

- core/components/com_citations/site/controllers/import.php
- core/plugins/citation/bibtex/bibtex.php
For larger imports, PHP could run out of memory due to caching the
results from prior queries. They aren't needed int his case, so disable
and flush the cache before each lookup.
Fixes: https://help.hubzero.org/support/ticket/11851
> [fix] Disable caching to free up memory

- core/components/com_login/site/controllers/auth.php
- core/components/com_users/site/controllers/auth.php
This needs setting on `this` so 3rd-party authenitcator plugins can
add it to the service URL.
Fixes: https://purr.purdue.edu/support/ticket/2049
> [fix] Set return value

- core/components/com_projects/helpers/githelper.php
This fixes issues with directory names that have spaces in them.
Fixes: https://purr.purdue.edu/support/ticket/2064
> [fix] Escape shell arguments

- core/components/com_publications/models/attachments/data.php
When creating a new version of a 'database', the `save()` method on the
`com_publications/models/attachments/data.php` model never gets invoked
and, consequently, doesn't create the needed directory for data to be
copied/written to. This causes file transfers to not produce anything.
The fix is to create the needed directory, if it doesn't exist, in the
`transferData` method of the same model.
Refs: https://purr.purdue.edu/support/ticket/1963
> [fix] Create needed path for files to be copied to

- core/plugins/oaipmh/publications/data/miner.php
The OAI-PMH metadata record harvesting returns wrong tags for the dataset/publication or does not return any tags in metadata record. Details in ticket: https://purr.purdue.edu/support/ticket/2078
> Fix the issue that wrong tags or null returned in OAI-PMH query result

- core/components/com_cron/commands/jobs.php
Allows various cron job tasks to be performed from the command line.
Syntax is:
`muse cron:jobs {task} {options}`
Current tasks include:
* Running pending jobs
* Running a specified job (ignore pending status)
* Listing jobs (pending or all)
* Marking a job as inactive
* Unpublishing a job
This is dependent upon a Framework change.
Refs: https://github.com/hubzero/framework/pull/599
> [feat] Command line (muse) utility for com_cron

- core/components/com_usage/helpers/verb.php
This fixed a /usage problem on nanohub.
> removing predis autoloader since this is already handled by composer

- core/components/com_content/admin/views/articles/tmpl/default.php
The duplicate attributes would cause the JS to not properly find select
elements that should auto-submit the form on change.
> [fix] Removing duplicate `class` attribute

- core/components/com_courses/models/prerequisite.php
The switch, with its breaks would cause PHP 7.2+ to throw a
`"continue" targeting switch is equivalent to "break". Did you mean to
use "continue 2"?` error. The switch is also entirely unnecessary in
this case and refactoring to a simple if statement resolves the issue.
> [refactor][fix] Prevent PHP 7.2+ from freaking out

- core/modules/mod_menu/mod_menu.xml
This allows config field type of 'menu' to properly render when editing
modules of type mod_menu.
> [fix] Add form field path for needed field type

- core/components/com_resources/models/entry.php
A user noticed that the author list displayed on the Contributors step
of the tool pipeline did not agree with the preview displayed during the
Finalize step of the pipeline
This change synchronizes the data source used to retrieve the authors in
the mentioned steps
fixes: https://mygeohub.org/support/ticket/1600
> [com_resources] Synchronize author data source

- core/components/com_publications/site/views/view/tmpl/default.php
Truncated tags can interfere with the rendering of the page
related to: ext learn publication video embedding issue
> Strip tags from at a glance content

- core/components/com_publications/models/blocks/citations.php
- core/components/com_publications/models/publication.php
purr.purdue.edu/support/ticket/2134
> Attach citations to publication versions

- core/plugins/groups/calendar/calendar.php
- core/plugins/groups/calendar/helpers/userLocalizer.php
- core/plugins/groups/calendar/views/calendar/tmpl/display.php
fixes: https://qubeshub.org/support/tickets/1673
> Localize group calendar event times

- core/components/com_resources/site/controllers/create.php
The previous query returned an array of arrays, so the in array check
would fail for any associated tags
fixes: https://nanohub.org/support/ticket/363378
> Update tag name lookup query

- core/templates/kameleon/js/index.js
Fixes non-working admin mobile menu. Fixes https://help.hubzero.org/support/ticket/11981
> Make the mobile menu in admin work as intended

- core/components/com_collections/models/asset.php
sha256 hash creates a URL greater than 255 characters on the communityhub.purdue.edu and attempting to download a file results failure (0Kb file).
> Fixes Comhub collection hash file download failure

- core/components/com_resources/admin/views/imports/tmpl/run.php
record.contributors array doesn't contain authors names
fixes: https://habricentral.org/support/ticket/875
> Update import result rendering

- core/migrations/Migration20200917000000AuthLinkIndex.php
- core/migrations/Migration20200917100000AuthDomainIndex.php
Muse requires that file names and class names match. This also removes
an unnecessary extra blank line and adds the docblocks to the `up` and
`down` methods.
> [fix] Fix class name not matching file name

- core/bootstrap/Administrator/routes.php
Routes would not be correctly built when going to /admin, resulting in
the login form submitting to the front-end. This would result in failed
logins (usually a CSRF token error).
> [fix] Allow login from "/admin"

- core/assets/js/contentbox.js
- core/plugins/courses/outline/assets/js/build.js
fixes https://nanohub.org/support/ticket/377476
> Make sure CKEDITOR works in content box

- core/composer.json
- core/composer.lock
This is a minor revision update to nao-pon/flysystem-google-drive among the fixes includes a fix to remove deprecated API batch request.
> update nao-pon/flysystem-google-drive to 1.1.13 to fix google API deprecation

- core/composer.json
- core/composer.lock
Update Swiftmailer package to 5.4.12 to fix stemedhub #721 (crlf corrupting subject header)
Selected last major version supporting PHP 5.6 (v5)
Selected last minor version without security flags (v5.4)
Selected latest revision.
> update swiftmailer to 5.4.12 to fix subject crlf and security issues

- core/composer.json
- core/composer.lock
The is a split from PR 1391 for just phpspreadsheet.
Upgrade phpoffice/phpspreadsheet to version 1.8.0 or later
CVE-2019-12331
moderate severity
Vulnerable versions: < 1.8.0
Patched version: 1.8.0
CVE-2018-19277
high severity
Vulnerable versions: < 1.5.0
Patched version: 1.5.0
securityScan() in PHPOffice PhpSpreadsheet through 1.5.0 allows a bypass of protection mechanisms for XXE via UTF-7 encoding in a .xlsx file
Selected version 1.8.2 as a minor update to 1.8.0 and last version supporting PHP 5.6
> update phpoffice/phpspreadsheet to 1.8.2

- core/composer.json
This was a dev requirement in for hubzero/framework. It doesn't exist in packagist and throws a composer error when explicitly listed in this json file. (maybe this is new behavior in latest version of composer, unsure).
This PR will need to be applied before other vendor package updates currently pending in order for composer to actually run correctly.
> hubzero/standards doesn't exist in packagist and causes composer errors here

- core/composer.json
- core/composer.lock
Upgrade symfony/http-foundation to version 2.8.52 or later unaffected version
CVE-2019-18888
moderate severity
Vulnerable versions: >= 2.0.0, < 2.8.52
Patched version: 2.8.52
> update symfony/http-foundation to v2.8.52

- core/components/com_resources/site/assets/css/video.css
- core/components/com_resources/site/assets/js/video.js
- core/components/com_resources/site/views/view/tmpl/video.php
Fixes https://cdmhub.org/support/ticket/2014
> Fix resources video for iOS

- core/components/com_groups/admin/controllers/modules.php
This mostly addresses an issue where creation of a new module would throw an under when using a database in strict mode. An empty string was being passed where strict mode expects the ID to be an integer or `null`.
PR includes some minor style and optimizations.
> [fix] Fix new modules under strict mode DB

- core/plugins/projects/files/connections.php
The expected return from the event trigger is an array of arrays (i.e., an array for each metadata plugin that responds). If no plugins are enabled or respond, this results in an empty array. The original line of code would assume a non-empty array.
As an aside, the line of code always takes the first respondent's metadata. If multiple plugins return data, you'll only get the first. I can't remember if this was intentional or not (Sam wrote that part, if memory serves). Still, it feels wrong. You'd probably want to merge all the returned data. Something to think about...
> fix(plg_projects_files): Ensure array is not empty
